### ISSUE TITLE
Make --prominent-compile-errors the default

### ISSUE THREAD

**Issue by silversquirl** [ziglang/zig#11392]
It's rare that I need to see the command that `zig build` failed on. I propose removing `--prominent-compile-errors`, which hides this command to make errors easier to read, and replacing it with the inverse: an option to *show* the failed command when an error occurs.

This new option could be named something like `--verbose-failure`, or this functionality could simply be removed, since it's kind of a subset of the normal `--verbose` option.

**Comment by andrewrk** [comment]
Solved by #14647 which puts compilation errors at the bottom. There is no longer any prominent-compile-errors option.

**Comment by hvbargen** [comment]
With Zig 0.14.1 I still get a lot of junk output after the errors when I call zig build:

Example:

```
PS C:\git-repos\tumirnix\exla\zig-lox> zig build
install
└─ install zig_lox
   └─ zig build-exe zig_lox Debug native 1 errors
src\vm.zig:238:22: error: union 'value.Value' has no member named 'greaterD'
        return Value.greaterD(right, left);
                     ^~~~~~~~
src\value.zig:14:19: note: union declared here
pub const Value = union(ValueType) {
                  ^~~~~
src\vm.zig:163:66: note: called from here
                .OP_LESS => self.push(Value{ .boolean = self.less() }),
                                                        ~~~~~~~~~^~
referenced by:
    interpret: src\vm.zig:63:24
    repl: src\main.zig:65:25
    5 reference(s) hidden; use '-freference-trace=7' to see all references
error: the following command failed with 1 compilation errors:
C:\Users\Henning\AppData\Roaming\Code\User\globalStorage\ziglang.vscode-zig\zig\x86_64-windows-0.14.1\zig.exe build-exe -ODebug --dep zig_lox_lib -Mroot=C:\git-repos\tumirnix\exla\zig-lox\src\main.zig -ODebug -Mzig_lox_lib=C:\git-repos\tumirnix\exla\zig-lox\src\root.zig --cache-dir C:\git-repos\tumirnix\exla\zig-lox\.zig-cache --global-cache-dir C:\Users\Henning\AppData\Local\zig --name zig_lox --zig-lib-dir C:\Users\Henning\AppData\Roaming\Code\User\globalStorage\ziglang.vscode-zig\zig\x86_64-windows-0.14.1\lib\ --listen=-
Build Summary: 2/5 steps succeeded; 1 failed
install transitive failure
└─ install zig_lox transitive failure
   └─ zig build-exe zig_lox Debug native 1 errors
error: the following build command failed with exit code 1:
C:\git-repos\tumirnix\exla\zig-lox\.zig-cache\o\fab8718fc83ed5666aca7ca6c11da1dc\build.exe C:\Users\Henning\AppData\Roaming\Code\User\globalStorage\ziglang.vscode-zig\zig\x86_64-windows-0.14.1\zig.exe C:\Users\Henning\AppData\Roaming\Code\User\globalStorage\ziglang.vscode-zig\zig\x86_64-windows-0.14.1\lib C:\git-repos\tumirnix\exla\zig-lox C:\git-repos\tumirnix\exla\zig-lox\.zig-cache C:\Users\Henning\AppData\Local\zig --seed 0xece9706c -Zce6fc2f8cb9180dc
PS C:\git-repos\tumirnix\exla\zig-lox> zig version
0.14.1

```


BTW  I'm using Robert Nystrom's excellent book "Crafting Interpreters", but in Zig instead of C.

**Comment by andrewrk** [comment]
it's not junk, it's essential troubleshooting information.

`--prominent-compile-errors` was reinstated, so you can use it to get the desired behavior.

it will not be the default.

**Comment by ivanstepanovftw** [comment]
- Invocation command (i.e. `/opt/zig-x86_64-linux-0.14.1/zig build-exe ...`) on the top and output (i.e. error message) on the bottom is the most common and recognizable pattern.

- Terminals do not have an option to disable word wrapping to collapse the invocation command under 1 line.

- Terminals scroll down for you. I cannot make an exception to not scroll when I use `zig build`.

Now I am using `--prominent-compile-errors` every time, so I am curious, why it will never be the default? 

<img width="2220" height="888" alt="Image" src="https://github.com/user-attachments/assets/af48bdab-db02-4d18-b477-d8b968b2ebc8" />
^ Just a showcase of default behavior, found this from #18160 . Here, I don't see error message details even at half the screen.

**Comment by andrewrk** [comment]
I see on the screenshot it says Visual Studio Code. Why are you using the terminal instead of the integrated errors pane for viewing errors? There's a shortcut key for viewing it, going to the next one, listing suggested fixes, etc.

**Comment by ivanstepanovftw** [comment]
Just tested it (Ctrl+Shift+M).
It works nice with `error: use of undeclared identifier 'mem'`. 
But some problems like `error: 'AppName' is not marked 'pub'` ... `note: declared here` aren't shown - "No problems have been detected in the workspace".
