### ISSUE TITLE
expected type 'type', found 'fn(comptime type) type' complains about wrong line

### ISSUE THREAD

**Issue by codethief** [ziglang/zig#14768]
### Zig Version

0.11.0-dev.1836+28364166e

### Steps to Reproduce and Observed Output

Hi there, I have a function

```
pub fn foo(param1: anytype, param2: bool) bool {
    var buffer: [200]u8 = undefined;
    const stream: std.io.FixedBufferStream = std.io.fixedBufferStream(&buffer);
    const writer = stream.writer();
    // ...
    return true;
}
```

and am getting the following error:

```
src/string_ops.zig:94:1: error: expected type 'type', found 'fn(comptime type) type'
pub fn foo(param1: anytype, param2: bool) bool {
^~~
``` 

I realize this is due std.io.FixedBufferStream, which is not a type but a function. However, the error message complains about `foo()`.

### Expected Output

```
src/string_ops.zig:xx:x: error: expected type 'type', found 'fn(comptime type) type'
    const stream: std.io.FixedBufferStream = std.io.fixedBufferStream(&buffer);
                             ^~~
```

**Comment by Daggerfall-is-the-best-TES-game** [comment]
On	zig-0.14.0-dev.144+a31fe8aa3 this is the error message I get, so this may have been fixed
```
src\main.zig:6:70: error: expected type 'type', found 'fn (comptime type) type'
    const stream: std.io.FixedBufferStream = std.io.fixedBufferStream(&buffer);
                                             ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
```

**Comment by codethief** [comment]
@Daggerfall-is-the-best-TES-game This still doesn't look correct, though. It should be complaining about the type on the LHS.

**Comment by Daggerfall-is-the-best-TES-game** [comment]
perhaps it's still broken, but in a different way now then.
