### ISSUE TITLE
zld: Overflow on zig c++ project to MacOS build

### ISSUE THREAD

**Issue by kassane** [ziglang/zig#15444]
### Zig Version

0.11.0-dev.2775+21aa55d34

### Steps to Reproduce and Observed Behavior

Ref.: https://github.com/kassane/outcome/issues/1

In CI testing there has been a linking issue for the macOS platform (`zld`) as opposed to the other platforms with (`lld`).
It only aims to port some C++ libraries to `zig build` with `zig-pkg` support.

`zig c++` verbosed:
<details>

```bash
zig c++ -Itest/quickcpplib/include test/tests/core-outcome.cpp -o core_test -target native-macos --verbose
clang version 16.0.1 (https://github.com/ziglang/zig-bootstrap 710c5d12660235bc4eac103a8c6677c61f0a9ded)
Target: x86_64-unknown-macosx11.7.1-unknown
Thread model: posix
InstalledDir: /usr/bin
 (in-process)
 "/home/kassane/zig/0.11.0-dev.2775+21aa55d34/files/zig" -cc1 -triple x86_64-unknown-macosx11.7.1-unknown -Wundef-prefix=TARGET_OS_ -Werror=undef-prefix -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name core-outcome.cpp -mrelocation-model pic -pic-level 2 -mframe-pointer=all -ffp-contract=on -fno-rounding-math -funwind-tables=2 -fcompatibility-qualified-id-block-type-checking -fvisibility-inlines-hidden-static-local-var -target-cpu penryn -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debug-info-kind=standalone -dwarf-version=4 -debugger-tuning=lldb -v -fcoverage-compilation-dir=/home/kassane/outcome -nostdsysteminc -nobuiltininc -resource-dir /home/kassane/zig/0.11.0-dev.2775+21aa55d34/lib/clang/16 -dependency-file /home/kassane/.cache/zig/tmp/f3fffd30308ca644-core-outcome.o.d -MT /home/kassane/.cache/zig/tmp/f3fffd30308ca644-core-outcome.o -sys-header-deps -MV -isystem /home/kassane/zig/0.11.0-dev.2775+21aa55d34/files/lib/libcxx/include -isystem /home/kassane/zig/0.11.0-dev.2775+21aa55d34/files/lib/libcxxabi/include -isystem /home/kassane/zig/0.11.0-dev.2775+21aa55d34/files/lib/include -isystem /home/kassane/zig/0.11.0-dev.2775+21aa55d34/files/lib/libc/include/x86_64-macos.11-none -isystem /home/kassane/zig/0.11.0-dev.2775+21aa55d34/files/lib/libc/include/any-macos.11-any -isystem /home/kassane/zig/0.11.0-dev.2775+21aa55d34/files/lib/libc/include/any-macos-any -D _LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D _LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -D _LIBCPP_HAS_NO_VENDOR_AVAILABILITY_ANNOTATIONS -D _LIBCPP_ABI_VERSION=1 -D _LIBCPP_ABI_NAMESPACE=__1 -D _DEBUG -I test/quickcpplib/include -O0 -Wno-overriding-t-option -fdeprecated-macro -fdebug-compilation-dir=/home/kassane/outcome -ferror-limit 19 -fsanitize=alignment,array-bounds,bool,builtin,enum,float-cast-overflow,function,integer-divide-by-zero,nonnull-attribute,null,pointer-overflow,return,returns-nonnull-attribute,shift-base,shift-exponent,signed-integer-overflow,unreachable,vla-bound -fsanitize-trap=alignment,array-bounds,bool,builtin,enum,float-cast-overflow,function,integer-divide-by-zero,nonnull-attribute,null,pointer-overflow,return,returns-nonnull-attribute,shift-base,shift-exponent,signed-integer-overflow,unreachable,vla-bound -fno-sanitize-memory-param-retval -fno-sanitize-address-use-odr-indicator -stack-protector 2 -stack-protector-buffer-size 4 -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -fmax-type-align=16 -fcolor-diagnostics -fno-spell-checking -target-cpu znver3 -target-feature -16bit-mode -target-feature -32bit-mode -target-feature -3dnow -target-feature -3dnowa -target-feature +64bit -target-feature +adx -target-feature +aes -target-feature +allow-light-256-bit -target-feature -amx-bf16 -target-feature -amx-fp16 -target-feature -amx-int8 -target-feature -amx-tile -target-feature +avx -target-feature +avx2 -target-feature -avx512bf16 -target-feature -avx512bitalg -target-feature -avx512bw -target-feature -avx512cd -target-feature -avx512dq -target-feature -avx512er -target-feature -avx512f -target-feature -avx512fp16 -target-feature -avx512ifma -target-feature -avx512pf -target-feature -avx512vbmi -target-feature -avx512vbmi2 -target-feature -avx512vl -target-feature -avx512vnni -target-feature -avx512vp2intersect -target-feature -avx512vpopcntdq -target-feature -avxifma -target-feature -avxneconvert -target-feature -avxvnni -target-feature -avxvnniint8 -target-feature +bmi -target-feature +bmi2 -target-feature +branchfusion -target-feature -cldemote -target-feature +clflushopt -target-feature +clwb -target-feature +clzero -target-feature +cmov -target-feature -cmpccxadd -target-feature +crc32 -target-feature +cx16 -target-feature +cx8 -target-feature -enqcmd -target-feature -ermsb -target-feature +f16c -target-feature -false-deps-getmant -target-feature -false-deps-lzcnt-tzcnt -target-feature -false-deps-mulc -target-feature -false-deps-mullq -target-feature -false-deps-perm -target-feature -false-deps-popcnt -target-feature -false-deps-range -target-feature -fast-11bytenop -target-feature +fast-15bytenop -target-feature -fast-7bytenop -target-feature +fast-bextr -target-feature -fast-gather -target-feature -fast-hops -target-feature +fast-lzcnt -target-feature +fast-movbe -target-feature +fast-scalar-fsqrt -target-feature +fast-scalar-shift-masks -target-feature -fast-shld-rotate -target-feature -fast-variable-crosslane-shuffle -target-feature +fast-variable-perlane-shuffle -target-feature +fast-vector-fsqrt -target-feature -fast-vector-shift-masks -target-feature +fma -target-feature -fma4 -target-feature +fsgsbase -target-feature +fsrm -target-feature +fxsr -target-feature -gfni -target-feature -harden-sls-ijmp -target-feature -harden-sls-ret -target-feature -hreset -target-feature -idivl-to-divb -target-feature -idivq-to-divl -target-feature +invpcid -target-feature -kl -target-feature -lea-sp -target-feature -lea-uses-ag -target-feature -lvi-cfi -target-feature -lvi-load-hardening -target-feature -lwp -target-feature +lzcnt -target-feature +macrofusion -target-feature +mmx -target-feature +movbe -target-feature -movdir64b -target-feature -movdiri -target-feature -mwaitx -target-feature +nopl -target-feature -pad-short-functions -target-feature +pclmul -target-feature -pconfig -target-feature -pku -target-feature +popcnt -target-feature -prefer-128-bit -target-feature -prefer-256-bit -target-feature -prefer-mask-registers -target-feature -prefetchi -target-feature -prefetchwt1 -target-feature +prfchw -target-feature -ptwrite -target-feature -raoint -target-feature +rdpid -target-feature +rdpru -target-feature +rdrnd -target-feature +rdseed -target-feature -retpoline -target-feature -retpoline-external-thunk -target-feature -retpoline-indirect-branches -target-feature -retpoline-indirect-calls -target-feature -rtm -target-feature +sahf -target-feature +sbb-dep-breaking -target-feature -serialize -target-feature -seses -target-feature -sgx -target-feature +sha -target-feature +shstk -target-feature -slow-3ops-lea -target-feature -slow-incdec -target-feature -slow-lea -target-feature -slow-pmaddwd -target-feature -slow-pmulld -target-feature +slow-shld -target-feature -slow-two-mem-ops -target-feature -slow-unaligned-mem-16 -target-feature -slow-unaligned-mem-32 -target-feature -soft-float -target-feature +sse -target-feature +sse2 -target-feature +sse3 -target-feature +sse4.1 -target-feature +sse4.2 -target-feature +sse4a -target-feature -sse-unaligned-mem -target-feature +ssse3 -target-feature -tagged-globals -target-feature -tbm -target-feature -tsxldtrk -target-feature -uintr -target-feature -use-glm-div-sqrt-costs -target-feature -use-slm-arith-costs -target-feature +vaes -target-feature +vpclmulqdq -target-feature +vzeroupper -target-feature -waitpkg -target-feature -wbnoinvd -target-feature -widekl -target-feature +x87 -target-feature -xop -target-feature +xsave -target-feature +xsavec -target-feature +xsaveopt -target-feature +xsaves -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /home/kassane/.cache/zig/tmp/f3fffd30308ca644-core-outcome.o -x c++ test/tests/core-outcome.cpp
clang -cc1 version 16.0.1 based upon LLVM 16.0.1 default target x86_64-linux-musl
#include "..." search starts here:
#include <...> search starts here:
 test/quickcpplib/include
 /home/kassane/zig/0.11.0-dev.2775+21aa55d34/files/lib/libcxx/include
 /home/kassane/zig/0.11.0-dev.2775+21aa55d34/files/lib/libcxxabi/include
 /home/kassane/zig/0.11.0-dev.2775+21aa55d34/files/lib/include
 /home/kassane/zig/0.11.0-dev.2775+21aa55d34/files/lib/libc/include/x86_64-macos.11-none
 /home/kassane/zig/0.11.0-dev.2775+21aa55d34/files/lib/libc/include/any-macos.11-any
 /home/kassane/zig/0.11.0-dev.2775+21aa55d34/files/lib/libc/include/any-macos-any
End of search list.
Compile C Objects [47/47] ar rcs /home/kassane/.cache/zig/o/75efd0a285ea3826040324d8c82beb47/libc++.a /home/kassane/.cache/zig/o/9c95545e22037f7f55ac9f261d0e371b/algorithm.o /home/kassane/.cache/zig/o/91fbadfda8fdc692b9b8cf287e0d95f4/any.o /home/kassane/.cache/zig/o/fe56f49e5a56e11841a8427206b3536d/atomic.o /home/kassane/.cache/zig/o/c4dbb21059a9ef2514e9c3c4ef9a1115/barrier.o /home/kassane/.cache/zig/o/12f1ce17b562db4962d172dbacda7875/bind.o /home/kassane/.cache/zig/o/c7487deaae1ef7ea0776a103c2a1e3ae/charconv.o /home/kassane/.cache/zig/o/07b13d22aee19d4c516caaff58793af7/chrono.o /home/kassane/.cache/zig/o/761acadb35197ae1a7294195c0b5d2f3/condition_variable.o /home/kassane/.cache/zig/o/c142a7c2d802f93047353ecded59fd50/condition_variable_destructor.o /home/kassane/.cache/zig/o/59caaaeb1f8e62131b21365226b49b54/debug.o /home/kassane/.cache/zig/o/a495cdc9d8b36343a16c34d506617362/exception.o /home/kassane/.cache/zig/o/041511ddfcff046bd5342983f362d232/memory_resource.o /home/kassane/.cache/zig/o/8835569bc24b49d9b510b4d59b65e0be/directory_iterator.o /home/kassane/.cache/zig/o/0126561244fad8ae49c4c94e9dea2925/operations.o /home/kassane/.cache/zig/o/f121dc86f05671369e531a462ba58fe7/format.o /home/kassane/.cache/zig/o/9a2106a6bd1a0f6950ac1f3d6c05ce05/functional.o /home/kassane/.cache/zig/o/1fd78071d52a6534e1617e6d5d94634e/future.o /home/kassane/.cache/zig/o/6b63c4e08cfc95a2a5ad76d5d2c5fbfa/hash.o /home/kassane/.cache/zig/o/587d0d804aa0cfdfa3654eddb6609343/ios.o /home/kassane/.cache/zig/o/1b8b8d2bedbe64767336a060f8ae5262/ios.instantiations.o /home/kassane/.cache/zig/o/6c6b50a85e7fed8ca26671374b1b4921/iostream.o /home/kassane/.cache/zig/o/9b0f1c8bc13434846c4a2398151fbd64/legacy_debug_handler.o /home/kassane/.cache/zig/o/bfaeb9ac84d137b2734cf2c4c2840e72/legacy_pointer_safety.o /home/kassane/.cache/zig/o/dfe2c092dccf0906a5a68ec37cbe5aaf/locale.o /home/kassane/.cache/zig/o/8b7539f8cae16af4040cea07c45c8eff/memory.o /home/kassane/.cache/zig/o/124dc6cec56f8adb900e84ec40205bec/mutex.o /home/kassane/.cache/zig/o/8a707066865ded5155ffd4bc5787609a/mutex_destructor.o /home/kassane/.cache/zig/o/8d0eaf1a372fd52f9e67248d03758c9a/new.o /home/kassane/.cache/zig/o/8f207fb546a5c7933986cb72fcbf89d2/optional.o /home/kassane/.cache/zig/o/1fae252967c13190d2780715cf70fb57/random.o /home/kassane/.cache/zig/o/b847789557dbbeccf2cae7879d16786c/random_shuffle.o /home/kassane/.cache/zig/o/49d154027dbc34c688d4c297d2062d7f/regex.o /home/kassane/.cache/zig/o/4f5d42843d46244a8d87aff4be628775/d2fixed.o /home/kassane/.cache/zig/o/06f352ad90061ac4bd6008ef2caf625c/d2s.o /home/kassane/.cache/zig/o/59366c38b2ca87892f5399a9ad29711a/f2s.o /home/kassane/.cache/zig/o/b93e7d3795895ea87c7acb8cb414ca33/shared_mutex.o /home/kassane/.cache/zig/o/ddafac54b744e40660c06f0b526f2aef/stdexcept.o /home/kassane/.cache/zig/o/be422a33fd3933fad9d9702b75c2c886/string.o /home/kassane/.cache/zig/o/a2a7fda71e5c9181bbbb8a42fe8beef7/strstream.o /home/kassane/.cache/zig/o/b475339b2d7e7bcbc9433b577e3fda5a/system_error.o /home/kassane/.cache/zig/o/b3851e1ea8ccd342a41663e6bf693495/thread.o /home/kassane/.cache/zig/o/6704d86e4f03d0a56d08b85720f9a9db/typeinfo.o /home/kassane/.cache/zig/o/6e747f9417924a6628ebe7924adf1c22/utility.o /home/kassane/.cache/zig/o/898452f32ac9aa8781cc55a326bc3c34/valarray.o /home/kassane/.cache/zig/o/d512eec3ea5d0133ffe652d973621e15/variant.o /home/kassane/.cache/zig/o/67d4d718d96ffc73fe80153a155f472b/vector.o /home/kassane/.cache/zig/o/6e982bbd2fe1e71b5978d92702d5fb1c/verbose_abort.o
Compile C Objects [19/19] ar rcs /home/kassane/.cache/zig/o/60aabdf62d8adcee929656ff4536d98c/libc++abi.a /home/kassane/.cache/zig/o/a8c58f76434c1ebe6d839a659b290529/abort_message.o /home/kassane/.cache/zig/o/30d62854830b3a1a6e18b39a27770e8d/cxa_aux_runtime.o /home/kassane/.cache/zig/o/2513ada76c36b8f597f806275d9bb1a9/cxa_default_handlers.o /home/kassane/.cache/zig/o/7a1ee96d2f368ce99843c0b2db99c868/cxa_demangle.o /home/kassane/.cache/zig/o/0b23b17c95a36b7639c98033a303b828/cxa_exception.o /home/kassane/.cache/zig/o/566202e032a2d03ed11540e05746cdd7/cxa_exception_storage.o /home/kassane/.cache/zig/o/dbe8b8418fb31d6925f8d31ab4347f29/cxa_guard.o /home/kassane/.cache/zig/o/ce4cfee2b5b716d1c8a080d354b50074/cxa_handlers.o /home/kassane/.cache/zig/o/9ab60c7c7979b912001a4190c7465c1f/cxa_noexception.o /home/kassane/.cache/zig/o/3275e22d4500e024e77ab225d98823bf/cxa_personality.o /home/kassane/.cache/zig/o/13d4c8b62f5ed39c3ad39ee5583132c7/cxa_thread_atexit.o /home/kassane/.cache/zig/o/0d28c9d4be495e23dfe1e27a915d2318/cxa_vector.o /home/kassane/.cache/zig/o/4c489486349f674cd654a3067bcd882d/cxa_virtual.o /home/kassane/.cache/zig/o/2fb5dfbe098d5c2715f48f11142ea159/fallback_malloc.o /home/kassane/.cache/zig/o/c7d832994f8a297e8fd67ef7ef82e51b/private_typeinfo.o /home/kassane/.cache/zig/o/47231c512f88af8c73fa819be5f114f9/stdlib_exception.o /home/kassane/.cache/zig/o/35a046896e3b2dcda4a9e876f31921fa/stdlib_new_delete.o /home/kassane/.cache/zig/o/1078d31870e58dac990582a5d2f61f3d/stdlib_stdexcept.o /home/kassane/.cache/zig/o/4dff00270e158752bc995794655831d4/stdlib_typeinfo.o
LLVM Emit Object... ar rcs /home/kassane/.cache/zig/o/9d8ec8f9c6138e12b1eec21482b8ae9d/libcompiler_rt.a /home/kassane/.cache/zig/o/9d8ec8f9c6138e12b1eec21482b8ae9d/libcompiler_rt.a.o
MachO Flush... zig ld -dynamic /home/kassane/.cache/zig/o/1ace304ecb84d9bb74e45ab5719f4d2d/core-outcome.o /home/kassane/.cache/zig/o/9d8ec8f9c6138e12b1eec21482b8ae9d/libcompiler_rt.a /home/kassane/.cache/zig/o/60aabdf62d8adcee929656ff4536d98c/libc++abi.a /home/kassane/.cache/zig/o/75efd0a285ea3826040324d8c82beb47/libc++.a -o core_test -lSystem -lc
error: Overflow
```
</details>

`zig build -fsummary`:
<details>

```bash
zig build -DTests -fsummary -freference-trace
zig build-exe core-outcome Debug native: error: error: Overflow

zig build-exe core-outcome Debug native: error: the following command exited with error code 1:
/Users/runner/hostedtoolcache/zig/zig-macos-x86_64-0.11.0-dev.2725+4374ce51b/x64/zig build-exe -freference-trace=256 -cflags -Wall -Wextra -- /Users/runner/work/outcome/outcome/test/tests/core-outcome.cpp -lc++ --cache-dir /Users/runner/work/outcome/outcome/zig-cache --global-cache-dir /Users/runner/.cache/zig --name core-outcome -I /Users/runner/work/outcome/outcome/test/quickcpplib/include -I /Users/runner/work/outcome/outcome/test/quickcpplib/include/quickcpplib --listen=- 
Build Summary: 81/84 steps succeeded; 1 failed
install transitive failure
+- install single-header/ success
+- install single-header-test success
|  +- zig build-exe single-header-test Debug native success 1m MaxRSS:135M
+- install WG21_P1886a success
|  +- zig build-exe WG21_P1886a Debug native success 1m MaxRSS:93M
+- install coroutine-support success
|  +- zig build-exe coroutine-support Debug native success 6s MaxRSS:87M
+- install comparison success
|  +- zig build-exe comparison Debug native success 19s MaxRSS:163M
+- install constexpr success
|  +- zig build-exe constexpr Debug native success 18s MaxRSS:162M
+- install core-outcome transitive failure
|  +- zig build-exe core-outcome Debug native failure
+- install core-result success
|  +- zig build-exe core-result Debug native success 15s MaxRSS:180M
+- install containers success
|  +- zig build-exe containers Debug native success 13s MaxRSS:160M
+- install hooks success
|  +- zig build-exe hooks Debug native success 13s MaxRSS:161M
+- install fileopen success
|  +- zig build-exe fileopen Debug native success 14s MaxRSS:154M
+- install default-construction success
|  +- zig build-exe default-construction Debug native success 14s MaxRSS:155M
+- install propagate success
|  +- zig build-exe propagate Debug native success 15s MaxRSS:165M
+- install serialisation success
|  +- zig build-exe serialisation Debug native success 14s MaxRSS:162M
+- install noexcept-propagation success
|  +- zig build-exe noexcept-propagation Debug native success 13s MaxRSS:157M
+- install swap success
|  +- zig build-exe swap Debug native success 15s MaxRSS:172M
+- install udts success
|  +- zig build-exe udts Debug native success 13s MaxRSS:159M
+- install success-failure success
|  +- zig build-exe success-failure Debug native success 12s MaxRSS:151M
+- install value-or-error success
|  +- zig build-exe value-or-error Debug native success 13s MaxRSS:157M
+- install expected-pass success
|  +- zig build-exe expected-pass Debug native success 13s MaxRSS:167M
+- install issue0007 success
|  +- zig build-exe issue0007 Debug native success 15s MaxRSS:160M
+- install issue0009 success
|  +- zig build-exe issue0009 Debug native success 14s MaxRSS:155M
+- install issue0010 success
|  +- zig build-exe issue0010 Debug native success 14s MaxRSS:154M
+- install issue0012 success
|  +- zig build-exe issue0012 Debug native success 13s MaxRSS:155M
+- install issue0016 success
|  +- zig build-exe issue0016 Debug native success 13s MaxRSS:153M
+- install issue0059 success
|  +- zig build-exe issue0059 Debug native success 13s MaxRSS:155M
+- install issue0061 success
|  +- zig build-exe issue0061 Debug native success 14s MaxRSS:163M
+- install issue0064 success
|  +- zig build-exe issue0064 Debug native success 13s MaxRSS:158M
+- install issue0065 success
|  +- zig build-exe issue0065 Debug native success 13s MaxRSS:156M
+- install issue0071 success
|  +- zig build-exe issue0071 Debug native success 14s MaxRSS:152M
+- install issue0095 success
|  +- zig build-exe issue0095 Debug native success 14s MaxRSS:154M
+- install issue0115 success
|  +- zig build-exe issue0115 Debug native success 14s MaxRSS:158M
+- install issue0116 success
|  +- zig build-exe issue0116 Debug native success 14s MaxRSS:156M
+- install issue0140 success
|  +- zig build-exe issue0140 Debug native success 14s MaxRSS:155M
+- install issue0182 success
|  +- zig build-exe issue0182 Debug native success 14s MaxRSS:152M
+- install issue0203 success
|  +- zig build-exe issue0203 Debug native success 14s MaxRSS:154M
+- install issue0210 success
|  +- zig build-exe issue0210 Debug native success 14s MaxRSS:159M
+- install issue0220 success
|  +- zig build-exe issue0220 Debug native success 14s MaxRSS:156M
+- install issue0244 success
|  +- zig build-exe issue0244 Debug native success 17s MaxRSS:162M
+- install issue0247 success
|  +- zig build-exe issue0247 Debug native success 15s MaxRSS:158M
+- install issue0255 success
|  +- zig build-exe issue0255 Debug native success 13s MaxRSS:152M
+- install issue0259 success
   +- zig build-exe issue0259 Debug native success 1m MaxRSS:172M
error: the following build command failed with exit code 1:
/Users/runner/work/outcome/outcome/zig-cache/o/19ee202b423125ea3c26de38fb262649/build /Users/runner/hostedtoolcache/zig/zig-macos-x86_64-0.11.0-dev.2725+4374ce51b/x64/zig /Users/runner/work/outcome/outcome /Users/runner/work/outcome/outcome/zig-cache /Users/runner/.cache/zig -DTests -fsummary -freference-trace -freference-trace
```
</details>

### Expected Behavior

Zig c++
<details>

```bash
zig c++ -Itest/quickcpplib/include test/tests/core-outcome.cpp -o core_test -target native-macos --verbose
clang version 16.0.1 (https://github.com/ziglang/zig-bootstrap 710c5d12660235bc4eac103a8c6677c61f0a9ded)
Target: x86_64-unknown-macosx11.7.1-unknown
Thread model: posix
InstalledDir: /usr/bin
 (in-process)
 "/home/kassane/zig/0.11.0-dev.2775+21aa55d34/files/zig" -cc1 -triple x86_64-unknown-macosx11.7.1-unknown -Wundef-prefix=TARGET_OS_ -Werror=undef-prefix -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name core-outcome.cpp -mrelocation-model pic -pic-level 2 -mframe-pointer=all -ffp-contract=on -fno-rounding-math -funwind-tables=2 -fcompatibility-qualified-id-block-type-checking -fvisibility-inlines-hidden-static-local-var -target-cpu penryn -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debug-info-kind=standalone -dwarf-version=4 -debugger-tuning=lldb -v -fcoverage-compilation-dir=/home/kassane/outcome -nostdsysteminc -nobuiltininc -resource-dir /home/kassane/zig/0.11.0-dev.2775+21aa55d34/lib/clang/16 -dependency-file /home/kassane/.cache/zig/tmp/f3fffd30308ca644-core-outcome.o.d -MT /home/kassane/.cache/zig/tmp/f3fffd30308ca644-core-outcome.o -sys-header-deps -MV -isystem /home/kassane/zig/0.11.0-dev.2775+21aa55d34/files/lib/libcxx/include -isystem /home/kassane/zig/0.11.0-dev.2775+21aa55d34/files/lib/libcxxabi/include -isystem /home/kassane/zig/0.11.0-dev.2775+21aa55d34/files/lib/include -isystem /home/kassane/zig/0.11.0-dev.2775+21aa55d34/files/lib/libc/include/x86_64-macos.11-none -isystem /home/kassane/zig/0.11.0-dev.2775+21aa55d34/files/lib/libc/include/any-macos.11-any -isystem /home/kassane/zig/0.11.0-dev.2775+21aa55d34/files/lib/libc/include/any-macos-any -D _LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D _LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -D _LIBCPP_HAS_NO_VENDOR_AVAILABILITY_ANNOTATIONS -D _LIBCPP_ABI_VERSION=1 -D _LIBCPP_ABI_NAMESPACE=__1 -D _DEBUG -I test/quickcpplib/include -O0 -Wno-overriding-t-option -fdeprecated-macro -fdebug-compilation-dir=/home/kassane/outcome -ferror-limit 19 -fsanitize=alignment,array-bounds,bool,builtin,enum,float-cast-overflow,function,integer-divide-by-zero,nonnull-attribute,null,pointer-overflow,return,returns-nonnull-attribute,shift-base,shift-exponent,signed-integer-overflow,unreachable,vla-bound -fsanitize-trap=alignment,array-bounds,bool,builtin,enum,float-cast-overflow,function,integer-divide-by-zero,nonnull-attribute,null,pointer-overflow,return,returns-nonnull-attribute,shift-base,shift-exponent,signed-integer-overflow,unreachable,vla-bound -fno-sanitize-memory-param-retval -fno-sanitize-address-use-odr-indicator -stack-protector 2 -stack-protector-buffer-size 4 -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -fmax-type-align=16 -fcolor-diagnostics -fno-spell-checking -target-cpu znver3 -target-feature -16bit-mode -target-feature -32bit-mode -target-feature -3dnow -target-feature -3dnowa -target-feature +64bit -target-feature +adx -target-feature +aes -target-feature +allow-light-256-bit -target-feature -amx-bf16 -target-feature -amx-fp16 -target-feature -amx-int8 -target-feature -amx-tile -target-feature +avx -target-feature +avx2 -target-feature -avx512bf16 -target-feature -avx512bitalg -target-feature -avx512bw -target-feature -avx512cd -target-feature -avx512dq -target-feature -avx512er -target-feature -avx512f -target-feature -avx512fp16 -target-feature -avx512ifma -target-feature -avx512pf -target-feature -avx512vbmi -target-feature -avx512vbmi2 -target-feature -avx512vl -target-feature -avx512vnni -target-feature -avx512vp2intersect -target-feature -avx512vpopcntdq -target-feature -avxifma -target-feature -avxneconvert -target-feature -avxvnni -target-feature -avxvnniint8 -target-feature +bmi -target-feature +bmi2 -target-feature +branchfusion -target-feature -cldemote -target-feature +clflushopt -target-feature +clwb -target-feature +clzero -target-feature +cmov -target-feature -cmpccxadd -target-feature +crc32 -target-feature +cx16 -target-feature +cx8 -target-feature -enqcmd -target-feature -ermsb -target-feature +f16c -target-feature -false-deps-getmant -target-feature -false-deps-lzcnt-tzcnt -target-feature -false-deps-mulc -target-feature -false-deps-mullq -target-feature -false-deps-perm -target-feature -false-deps-popcnt -target-feature -false-deps-range -target-feature -fast-11bytenop -target-feature +fast-15bytenop -target-feature -fast-7bytenop -target-feature +fast-bextr -target-feature -fast-gather -target-feature -fast-hops -target-feature +fast-lzcnt -target-feature +fast-movbe -target-feature +fast-scalar-fsqrt -target-feature +fast-scalar-shift-masks -target-feature -fast-shld-rotate -target-feature -fast-variable-crosslane-shuffle -target-feature +fast-variable-perlane-shuffle -target-feature +fast-vector-fsqrt -target-feature -fast-vector-shift-masks -target-feature +fma -target-feature -fma4 -target-feature +fsgsbase -target-feature +fsrm -target-feature +fxsr -target-feature -gfni -target-feature -harden-sls-ijmp -target-feature -harden-sls-ret -target-feature -hreset -target-feature -idivl-to-divb -target-feature -idivq-to-divl -target-feature +invpcid -target-feature -kl -target-feature -lea-sp -target-feature -lea-uses-ag -target-feature -lvi-cfi -target-feature -lvi-load-hardening -target-feature -lwp -target-feature +lzcnt -target-feature +macrofusion -target-feature +mmx -target-feature +movbe -target-feature -movdir64b -target-feature -movdiri -target-feature -mwaitx -target-feature +nopl -target-feature -pad-short-functions -target-feature +pclmul -target-feature -pconfig -target-feature -pku -target-feature +popcnt -target-feature -prefer-128-bit -target-feature -prefer-256-bit -target-feature -prefer-mask-registers -target-feature -prefetchi -target-feature -prefetchwt1 -target-feature +prfchw -target-feature -ptwrite -target-feature -raoint -target-feature +rdpid -target-feature +rdpru -target-feature +rdrnd -target-feature +rdseed -target-feature -retpoline -target-feature -retpoline-external-thunk -target-feature -retpoline-indirect-branches -target-feature -retpoline-indirect-calls -target-feature -rtm -target-feature +sahf -target-feature +sbb-dep-breaking -target-feature -serialize -target-feature -seses -target-feature -sgx -target-feature +sha -target-feature +shstk -target-feature -slow-3ops-lea -target-feature -slow-incdec -target-feature -slow-lea -target-feature -slow-pmaddwd -target-feature -slow-pmulld -target-feature +slow-shld -target-feature -slow-two-mem-ops -target-feature -slow-unaligned-mem-16 -target-feature -slow-unaligned-mem-32 -target-feature -soft-float -target-feature +sse -target-feature +sse2 -target-feature +sse3 -target-feature +sse4.1 -target-feature +sse4.2 -target-feature +sse4a -target-feature -sse-unaligned-mem -target-feature +ssse3 -target-feature -tagged-globals -target-feature -tbm -target-feature -tsxldtrk -target-feature -uintr -target-feature -use-glm-div-sqrt-costs -target-feature -use-slm-arith-costs -target-feature +vaes -target-feature +vpclmulqdq -target-feature +vzeroupper -target-feature -waitpkg -target-feature -wbnoinvd -target-feature -widekl -target-feature +x87 -target-feature -xop -target-feature +xsave -target-feature +xsavec -target-feature +xsaveopt -target-feature +xsaves -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /home/kassane/.cache/zig/tmp/f3fffd30308ca644-core-outcome.o -x c++ test/tests/core-outcome.cpp
clang -cc1 version 16.0.1 based upon LLVM 16.0.1 default target x86_64-linux-musl
#include "..." search starts here:
#include <...> search starts here:
 test/quickcpplib/include
 /home/kassane/zig/0.11.0-dev.2775+21aa55d34/files/lib/libcxx/include
 /home/kassane/zig/0.11.0-dev.2775+21aa55d34/files/lib/libcxxabi/include
 /home/kassane/zig/0.11.0-dev.2775+21aa55d34/files/lib/include
 /home/kassane/zig/0.11.0-dev.2775+21aa55d34/files/lib/libc/include/x86_64-macos.11-none
 /home/kassane/zig/0.11.0-dev.2775+21aa55d34/files/lib/libc/include/any-macos.11-any
 /home/kassane/zig/0.11.0-dev.2775+21aa55d34/files/lib/libc/include/any-macos-any
End of search list.
Compile C Objects [47/47] ar rcs /home/kassane/.cache/zig/o/75efd0a285ea3826040324d8c82beb47/libc++.a /home/kassane/.cache/zig/o/9c95545e22037f7f55ac9f261d0e371b/algorithm.o /home/kassane/.cache/zig/o/91fbadfda8fdc692b9b8cf287e0d95f4/any.o /home/kassane/.cache/zig/o/fe56f49e5a56e11841a8427206b3536d/atomic.o /home/kassane/.cache/zig/o/c4dbb21059a9ef2514e9c3c4ef9a1115/barrier.o /home/kassane/.cache/zig/o/12f1ce17b562db4962d172dbacda7875/bind.o /home/kassane/.cache/zig/o/c7487deaae1ef7ea0776a103c2a1e3ae/charconv.o /home/kassane/.cache/zig/o/07b13d22aee19d4c516caaff58793af7/chrono.o /home/kassane/.cache/zig/o/761acadb35197ae1a7294195c0b5d2f3/condition_variable.o /home/kassane/.cache/zig/o/c142a7c2d802f93047353ecded59fd50/condition_variable_destructor.o /home/kassane/.cache/zig/o/59caaaeb1f8e62131b21365226b49b54/debug.o /home/kassane/.cache/zig/o/a495cdc9d8b36343a16c34d506617362/exception.o /home/kassane/.cache/zig/o/041511ddfcff046bd5342983f362d232/memory_resource.o /home/kassane/.cache/zig/o/8835569bc24b49d9b510b4d59b65e0be/directory_iterator.o /home/kassane/.cache/zig/o/0126561244fad8ae49c4c94e9dea2925/operations.o /home/kassane/.cache/zig/o/f121dc86f05671369e531a462ba58fe7/format.o /home/kassane/.cache/zig/o/9a2106a6bd1a0f6950ac1f3d6c05ce05/functional.o /home/kassane/.cache/zig/o/1fd78071d52a6534e1617e6d5d94634e/future.o /home/kassane/.cache/zig/o/6b63c4e08cfc95a2a5ad76d5d2c5fbfa/hash.o /home/kassane/.cache/zig/o/587d0d804aa0cfdfa3654eddb6609343/ios.o /home/kassane/.cache/zig/o/1b8b8d2bedbe64767336a060f8ae5262/ios.instantiations.o /home/kassane/.cache/zig/o/6c6b50a85e7fed8ca26671374b1b4921/iostream.o /home/kassane/.cache/zig/o/9b0f1c8bc13434846c4a2398151fbd64/legacy_debug_handler.o /home/kassane/.cache/zig/o/bfaeb9ac84d137b2734cf2c4c2840e72/legacy_pointer_safety.o /home/kassane/.cache/zig/o/dfe2c092dccf0906a5a68ec37cbe5aaf/locale.o /home/kassane/.cache/zig/o/8b7539f8cae16af4040cea07c45c8eff/memory.o /home/kassane/.cache/zig/o/124dc6cec56f8adb900e84ec40205bec/mutex.o /home/kassane/.cache/zig/o/8a707066865ded5155ffd4bc5787609a/mutex_destructor.o /home/kassane/.cache/zig/o/8d0eaf1a372fd52f9e67248d03758c9a/new.o /home/kassane/.cache/zig/o/8f207fb546a5c7933986cb72fcbf89d2/optional.o /home/kassane/.cache/zig/o/1fae252967c13190d2780715cf70fb57/random.o /home/kassane/.cache/zig/o/b847789557dbbeccf2cae7879d16786c/random_shuffle.o /home/kassane/.cache/zig/o/49d154027dbc34c688d4c297d2062d7f/regex.o /home/kassane/.cache/zig/o/4f5d42843d46244a8d87aff4be628775/d2fixed.o /home/kassane/.cache/zig/o/06f352ad90061ac4bd6008ef2caf625c/d2s.o /home/kassane/.cache/zig/o/59366c38b2ca87892f5399a9ad29711a/f2s.o /home/kassane/.cache/zig/o/b93e7d3795895ea87c7acb8cb414ca33/shared_mutex.o /home/kassane/.cache/zig/o/ddafac54b744e40660c06f0b526f2aef/stdexcept.o /home/kassane/.cache/zig/o/be422a33fd3933fad9d9702b75c2c886/string.o /home/kassane/.cache/zig/o/a2a7fda71e5c9181bbbb8a42fe8beef7/strstream.o /home/kassane/.cache/zig/o/b475339b2d7e7bcbc9433b577e3fda5a/system_error.o /home/kassane/.cache/zig/o/b3851e1ea8ccd342a41663e6bf693495/thread.o /home/kassane/.cache/zig/o/6704d86e4f03d0a56d08b85720f9a9db/typeinfo.o /home/kassane/.cache/zig/o/6e747f9417924a6628ebe7924adf1c22/utility.o /home/kassane/.cache/zig/o/898452f32ac9aa8781cc55a326bc3c34/valarray.o /home/kassane/.cache/zig/o/d512eec3ea5d0133ffe652d973621e15/variant.o /home/kassane/.cache/zig/o/67d4d718d96ffc73fe80153a155f472b/vector.o /home/kassane/.cache/zig/o/6e982bbd2fe1e71b5978d92702d5fb1c/verbose_abort.o
Compile C Objects [19/19] ar rcs /home/kassane/.cache/zig/o/60aabdf62d8adcee929656ff4536d98c/libc++abi.a /home/kassane/.cache/zig/o/a8c58f76434c1ebe6d839a659b290529/abort_message.o /home/kassane/.cache/zig/o/30d62854830b3a1a6e18b39a27770e8d/cxa_aux_runtime.o /home/kassane/.cache/zig/o/2513ada76c36b8f597f806275d9bb1a9/cxa_default_handlers.o /home/kassane/.cache/zig/o/7a1ee96d2f368ce99843c0b2db99c868/cxa_demangle.o /home/kassane/.cache/zig/o/0b23b17c95a36b7639c98033a303b828/cxa_exception.o /home/kassane/.cache/zig/o/566202e032a2d03ed11540e05746cdd7/cxa_exception_storage.o /home/kassane/.cache/zig/o/dbe8b8418fb31d6925f8d31ab4347f29/cxa_guard.o /home/kassane/.cache/zig/o/ce4cfee2b5b716d1c8a080d354b50074/cxa_handlers.o /home/kassane/.cache/zig/o/9ab60c7c7979b912001a4190c7465c1f/cxa_noexception.o /home/kassane/.cache/zig/o/3275e22d4500e024e77ab225d98823bf/cxa_personality.o /home/kassane/.cache/zig/o/13d4c8b62f5ed39c3ad39ee5583132c7/cxa_thread_atexit.o /home/kassane/.cache/zig/o/0d28c9d4be495e23dfe1e27a915d2318/cxa_vector.o /home/kassane/.cache/zig/o/4c489486349f674cd654a3067bcd882d/cxa_virtual.o /home/kassane/.cache/zig/o/2fb5dfbe098d5c2715f48f11142ea159/fallback_malloc.o /home/kassane/.cache/zig/o/c7d832994f8a297e8fd67ef7ef82e51b/private_typeinfo.o /home/kassane/.cache/zig/o/47231c512f88af8c73fa819be5f114f9/stdlib_exception.o /home/kassane/.cache/zig/o/35a046896e3b2dcda4a9e876f31921fa/stdlib_new_delete.o /home/kassane/.cache/zig/o/1078d31870e58dac990582a5d2f61f3d/stdlib_stdexcept.o /home/kassane/.cache/zig/o/4dff00270e158752bc995794655831d4/stdlib_typeinfo.o
LLVM Emit Object... ar rcs /home/kassane/.cache/zig/o/9d8ec8f9c6138e12b1eec21482b8ae9d/libcompiler_rt.a /home/kassane/.cache/zig/o/9d8ec8f9c6138e12b1eec21482b8ae9d/libcompiler_rt.a.o
MachO Flush... zig ld -dynamic /home/kassane/.cache/zig/o/1ace304ecb84d9bb74e45ab5719f4d2d/core-outcome.o /home/kassane/.cache/zig/o/9d8ec8f9c6138e12b1eec21482b8ae9d/libcompiler_rt.a /home/kassane/.cache/zig/o/60aabdf62d8adcee929656ff4536d98c/libc++abi.a /home/kassane/.cache/zig/o/75efd0a285ea3826040324d8c82beb47/libc++.a -o core_test -lSystem -lc
```
</details>

Zig build
<details>

```bash
$> zig build -DTests -fsummary -freference-trace
Build Summary: 84/84 steps succeeded
install success
+- install single-header/ success
+- install single-header-test success
|  +- zig build-exe single-header-test Debug native success 36s MaxRSS:118M
+- install WG21_P1886a success
|  +- zig build-exe WG21_P1886a Debug native success 36s MaxRSS:163M
+- install coroutine-support success
|  +- zig build-exe coroutine-support Debug native success 1s MaxRSS:115M
+- install comparison success
|  +- zig build-exe comparison Debug native success 3s MaxRSS:195M
+- install constexpr success
|  +- zig build-exe constexpr Debug native success 3s MaxRSS:190M
+- install core-outcome success
|  +- zig build-exe core-outcome Debug native success 4s MaxRSS:216M
+- install core-result success
|  +- zig build-exe core-result Debug native success 4s MaxRSS:210M
+- install containers success
|  +- zig build-exe containers Debug native success 3s MaxRSS:194M
+- install hooks success
|  +- zig build-exe hooks Debug native success 3s MaxRSS:195M
+- install fileopen success
|  +- zig build-exe fileopen Debug native success 3s MaxRSS:189M
+- install default-construction success
|  +- zig build-exe default-construction Debug native success 3s MaxRSS:184M
+- install propagate success
|  +- zig build-exe propagate Debug native success 3s MaxRSS:198M
+- install serialisation success
|  +- zig build-exe serialisation Debug native success 3s MaxRSS:193M
+- install noexcept-propagation success
|  +- zig build-exe noexcept-propagation Debug native success 3s MaxRSS:185M
+- install swap success
|  +- zig build-exe swap Debug native success 4s MaxRSS:204M
+- install udts success
|  +- zig build-exe udts Debug native success 3s MaxRSS:191M
+- install success-failure success
|  +- zig build-exe success-failure Debug native success 3s MaxRSS:181M
+- install value-or-error success
|  +- zig build-exe value-or-error Debug native success 3s MaxRSS:185M
+- install expected-pass success
|  +- zig build-exe expected-pass Debug native success 3s MaxRSS:197M
+- install issue0007 success
|  +- zig build-exe issue0007 Debug native success 3s MaxRSS:193M
+- install issue0009 success
|  +- zig build-exe issue0009 Debug native success 3s MaxRSS:184M
+- install issue0010 success
|  +- zig build-exe issue0010 Debug native success 3s MaxRSS:187M
+- install issue0012 success
|  +- zig build-exe issue0012 Debug native success 3s MaxRSS:190M
+- install issue0016 success
|  +- zig build-exe issue0016 Debug native success 3s MaxRSS:184M
+- install issue0059 success
|  +- zig build-exe issue0059 Debug native success 3s MaxRSS:184M
+- install issue0061 success
|  +- zig build-exe issue0061 Debug native success 3s MaxRSS:194M
+- install issue0064 success
|  +- zig build-exe issue0064 Debug native success 3s MaxRSS:189M
+- install issue0065 success
|  +- zig build-exe issue0065 Debug native success 3s MaxRSS:189M
+- install issue0071 success
|  +- zig build-exe issue0071 Debug native success 3s MaxRSS:181M
+- install issue0095 success
|  +- zig build-exe issue0095 Debug native success 3s MaxRSS:183M
+- install issue0115 success
|  +- zig build-exe issue0115 Debug native success 3s MaxRSS:191M
+- install issue0116 success
|  +- zig build-exe issue0116 Debug native success 3s MaxRSS:189M
+- install issue0140 success
|  +- zig build-exe issue0140 Debug native success 3s MaxRSS:186M
+- install issue0182 success
|  +- zig build-exe issue0182 Debug native success 3s MaxRSS:181M
+- install issue0203 success
|  +- zig build-exe issue0203 Debug native success 3s MaxRSS:185M
+- install issue0210 success
|  +- zig build-exe issue0210 Debug native success 3s MaxRSS:193M
+- install issue0220 success
|  +- zig build-exe issue0220 Debug native success 3s MaxRSS:191M
+- install issue0244 success
|  +- zig build-exe issue0244 Debug native success 3s MaxRSS:198M
+- install issue0247 success
|  +- zig build-exe issue0247 Debug native success 3s MaxRSS:190M
+- install issue0255 success
|  +- zig build-exe issue0255 Debug native success 3s MaxRSS:183M
+- install issue0259 success
   +- zig build-exe issue0259 Debug native success 3s MaxRSS:205M
```
</details>

**Comment by kubkon** [comment]
Nice, thanks! Can you provide detailed repro steps please, what to clone, etc.?

**Comment by kubkon** [comment]
> My fork library (header only) has `build.zig` to zig master
> 
> ```shell
> git clone https://github.com/kassane/outcome
> cd outcome
> zig build -DTests
> ```

You forgot to mention it uses submodules ;-)

**Comment by kubkon** [comment]
I just managed to build it without any problems on `aarch64-macos` which strongly suggests this is an `x86_64-macos` only issue - will investigate further!

**Comment by kubkon** [comment]
Hmm, cannot repro it when cross-compiling to `x86_64-macos` from `aarch64-macos` (macOS 13.1). Next, I'll try firing up one of my VMs with older version of macOS and see if I can at least repro the issue. Stay tuned!

**Comment by kubkon** [comment]
Fixed in #16113

**Comment by kassane** [comment]
Hi @kubkon ,

The issue still occurred in the latest build this week.
See that skip build for MacOS 
https://github.com/kassane/outcome/blob/zig-pkg/build.zig#L61-L84

**Comment by kubkon** [comment]
Original issue is now fixed (pending merge to master):

<img width="728" alt="Screenshot 2023-06-20 at 14 30 18" src="https://github.com/ziglang/zig/assets/1519747/90fc291f-d02f-4cae-b78a-f5ffd9b51cde">

However, uncommenting the remaining tests yields an undefined symbol error which is unrelated to this issue:

<img width="1728" alt="Screenshot 2023-06-20 at 14 32 47" src="https://github.com/ziglang/zig/assets/1519747/11db2785-6074-4f8f-981c-18fec385fe9a">

**Comment by kassane** [comment]
Indeed, the same error happened here.

**Comment by kassane** [comment]
Maybe this new patch does fix only integer overflow errors. Does it solve errors for any project, or not?
Here I'm running some tests with this fork and get the same error reported.
Please ignore that the Windows part needs refactoring because it has not been updated for 5 years by the original author.

https://github.com/kassane/cppcoro/actions/runs/5326694638/jobs/9649065181
```bash
# on macOS host-target
zig build -DTests --summary all -freference-trace
zig build-exe when_all_tests Debug native: error: error: Overflow

zig build-exe when_all_tests Debug native: error: the following command exited with error code 1:
/Users/runner/hostedtoolcache/zig/master/x64/zig build-exe -freference-trace=256 /Users/runner/work/cppcoro/cppcoro/zig-cache/o/23f2fee4f5acdac804e6df9cbc33baf4/libcppcoro.a -cflags -std=c++2b -Wall -Wextra -- /Users/runner/work/cppcoro/cppcoro/test/when_all_tests.cpp -cflags -std=c++2b -Wall -Wextra -- /Users/runner/work/cppcoro/cppcoro/test/main.cpp /Users/runner/work/cppcoro/cppcoro/test/counted.cpp -lc++ --cache-dir /Users/runner/work/cppcoro/cppcoro/zig-cache --global-cache-dir /Users/runner/.cache/zig --name when_all_tests -I /Users/runner/work/cppcoro/cppcoro/zig-out/include -I /Users/runner/work/cppcoro/cppcoro/include -I /Users/runner/work/cppcoro/cppcoro/lib -I /Users/runner/work/cppcoro/cppcoro/test -I /Users/runner/work/cppcoro/cppcoro/test/doctest --listen=- 
zig build-exe recursive_generator_tests Debug native: error: error: Overflow
```

**Comment by kubkon** [comment]
Can you rebuild your Zig in debug with this patch on and submit the stack trace please?

**Comment by kubkon** [comment]
Oh this is a different repo, lemme have a look.

**Comment by kubkon** [comment]
Everything passes fine for me locally with this PR applied.

**Comment by kassane** [comment]
> Everything still passes fine for me locally with this PR applied.

OK. I will test with PR tomorrow.
