### ISSUE TITLE
Zig build causes segfault on AMD-based WSL2

### ISSUE THREAD

**Issue by edyu** [ziglang/zig#15723]
### Zig Version

0.11.0-dev.3132+465272921

### Steps to Reproduce and Observed Behavior

This is more of informational than exact step. I don't know enough of the internals to pinpoint where the error originated from but maybe someone who does can see what would cause this problem.
I have 2 laptops (one has intel and the other has amd). Both run windows 11 and I use both with Ubuntu 22.04 LTS WSL2.
On one of them when I call zig build on for example the zigzap/zap repository, it would cause the following error:
`signal SIGSEGV (Address boundary error)`
However, after I installed gdb with `sudo apt install gdb` the problem went away.

### Expected Behavior

Should compile ok without installing gdb first.

**Comment by edyu** [comment]
Maybe it's caused by the new package manager and when .url in the .dependencies for a package is unavailable, it would cause this problem.
`'zig build' terminated by signal SIGSEGV (Address boundary error)`

**Comment by edyu** [comment]
> @edyu are you invoking `zig build` on package located in a windows folder or a subsystem folder?
> 
> 

On subsystem folder.

**Comment by edyu** [comment]
Honestly I'm not seeing the problem anymore but here is the config that would've have caused it.
<pre>
.{
    .name = "My example project",
    .version = "0.0.1",

    .dependencies = .{
        // zap release-0.0.20
        .zap = .{
            .url = "https://github.com/zigzap/zap/archive/refs/tags/release-0.0.20.tar.gz",
            .hash = "12200772b594bc50bbdc18b14aa3c7461991a33179f9c254de05eb34d214662971da",
        }
    }
}
</pre>

**Comment by DraagrenKirneh** [comment]
Can confirm that this is happening on WSL, where gdb is not present. 
```
zig init-exe
touch build.zig.zon
# copy the content from the comment above
zig build
# Segmentation fault (core dumped)
```
Builds as expected if I remove the zon file.

**Comment by nektro** [comment]
on linux that yields the following, though it is also weird how there's an extra line between the caret and the message

```
/home/meghan/src/temp/build.zig.zon:1:1: error: expected expression, found 'EOF'

^
```

**Comment by edyu** [comment]
As of zig version `0.11.0-dev.3206+b9d2e0e30`, I'm not seeing this problem anymore. Maybe it's related to the TLS fix.

**Comment by edyu** [comment]
Now the error is `error: TlsFailure` 
version is now  error: `0.11.0-dev.3286+dcc1b4fd1`

**Comment by edyu** [comment]
And sometimes `error: BadReaderState`

**Comment by DraagrenKirneh** [comment]
Looks like this is now fixed in latest master by:  https://github.com/ziglang/zig/commit/057d30bacc4d97f53c2e69585dc8d50186cfc7f5 

With it package download works, If i revert it I get `BadReaderState` etc.

**Comment by edyu** [comment]
Still having the following error at `0.11.0-dev.3312+ab37ab33c`
```'zig build' terminated by signal SIGSEGV (Address boundary error)```

```
.{
    .name = "mytest",
    .version = "0.0.2",

    .dependencies = .{
        // zap v0.1.4-pre
        .zap = .{
            .url = "https://github.com/zigzap/zap/archive/refs/tags/v0.1.4-pre.tar.gz",
            .hash = "12204613bae513282f2b7e468045401cbae09bb19e42baeca193b9c98ff6f2ceb6ef",
        }
    }
}
```

**Comment by edyu** [comment]
And I can confirm that if i replace the url with a localhost serving the tar.gz such as python and I change the `.url` to `http://localhost:8000/v0.1.4-pre.tar.gz`, the zig build would work. So it's most likely something screwy in the package fetching code.

**Comment by edyu** [comment]
btw, I'm running Ubuntu 22.04 LTS in WSL2 on an AMD 5800HS (not sure how relevant).

**Comment by edyu** [comment]
#15590

**Comment by renerocksai** [comment]
zig build segfaults at least 33% of the time if it needs to fetch packages. it has done so for a while. this issue was shadowed by more frequent TLS bugs before. I can't poinpoint to where exactly it is crashing until we get zig debug builds.

I run nightly CI builds and the chance of waking up to a segfaulted build is > 33%

**Comment by edyu** [comment]
One thing I know that segfault happens is when network is spotty. I believe one of the reason is that when network is spotty, the package fetched is either incomplete or 0 bytes and somehow the code is trying to read that which would cause segfault. I've noticed I can make this happen on my computer when my network is crappy but if it run it enough times, network would be intermittent ok and then it would be ok.

**Comment by edyu** [comment]
I want to show an example of the problem. This is from a new machine that was just setup so there is nothing in the zig cache. You can see `zig build` would segfault multiple times and eventually would work...
```
~/w/z/blocktube main• ❱ zig build
fish: Job 1, 'zig build' terminated by signal SIGSEGV (Address boundary error)
~/w/z/blocktube main• 3.8s | 139 ❱ zig build
fish: Job 1, 'zig build' terminated by signal SIGSEGV (Address boundary error)
~/w/z/blocktube main• 1.2s | 139 ❱ zig build
fish: Job 1, 'zig build' terminated by signal SIGSEGV (Address boundary error)
~/w/z/blocktube main• 1.2s | 139 ❱ zig build
fish: Job 1, 'zig build' terminated by signal SIGSEGV (Address boundary error)
~/w/z/blocktube main• 3s | 139 ❱ zig build
~/w/z/blocktube main• 38s ❱ ls
```

**Comment by andrewrk** [comment]
Can you reproduce the issue with a debug build of the compiler?

**Comment by edyu** [comment]
> Can you reproduce the issue with a debug build of the compiler?

If you can point me to what I need to do and I'll try.

**Comment by renerocksai** [comment]
> > Can you reproduce the issue with a debug build of the compiler?
> 
> If you can point me to what I need to do and I'll try.

Check out the zig wiki on GitHub. I would start here: https://github.com/ziglang/zig/wiki/Contributing#editing-source-code - contains a link to building from source but focusses on editing and running your modified version, e.g. when you put print debug statements in there etc.

**Comment by edyu** [comment]
0.11.0-dev.3879+5804f3f75 is the version I'm running now
