### ISSUE TITLE
Can not c header with aligned(1) integer types.

### ISSUE THREAD

**Issue by loongw** [ziglang/zig#1580]
I am trying to import an old c project header within something like this:
```c
// t.h
typedef unsigned char U8;
typedef unsigned short __attribute__((aligned(1))) U16;
typedef unsigned int __attribute__((aligned(1))) U32;

struct _comfirm_align1 {
    U8 a;
    U16 b;
    U32 c;
};

typedef int compiler_does_not_support_aligned1[sizeof(struct _comfirm_align1)==7?0:-1];
```
got error:
```
$ zig build-exe --verbose-cimport --libc-include-dir . hi.zig
D:\kevin\codes\zig\interop\hi.zig:2:11: error: C import failed
const c = @cImport({
          ^
.\t.h:11:48: note: 'compiler_does_not_support_aligned1' declared as an array with a negative size
typedef int compiler_does_not_support_aligned1[sizeof(struct _comfirm_align1)==7?0:-1];
```

this piece of c code works fine with gcc and clang.

translate-c has the same issue.

**Comment by wilsonk** [comment]
A quick update. It appears as though the error mentioned above is fixed, however another problem arises:

```
const std = @import("std");
const warn = std.debug.warn;

const c = @cImport({ 
    @cInclude("t.h");
     });

pub fn main() void {
    const x = c.compiler_does_not_support_aligned1;
    warn("aligned val {}\n", .{ x.* });
}
```
when trying to compile this example, x.* is imported simply as 'type' and not an 'int *' as it is in C. 
```
hi.zig:10:34: error: attempt to dereference non-pointer type 'type'
```
Not sure how to fix, or whether this issue should be closed and a new one opened for this new problem?

**Comment by Vexu** [comment]
`compiler_does_not_support_aligned1` is just `[0]c_int`

This example works correctly:
```c
// t.h
typedef unsigned char U8;
typedef unsigned short __attribute__((aligned(1))) U16;
typedef unsigned int __attribute__((aligned(1))) U32;

struct _comfirm_align1 {
    U8 a;
    U16 b;
    U32 c;
};

typedef int compiler_does_not_support_aligned1[sizeof(struct _comfirm_align1)==7?1:-1];
```
```zig
const std = @import("std");
const warn = std.debug.warn;

const c = @cImport({ 
    @cInclude("t.h");
});

pub fn main() void {
    const x: c.compiler_does_not_support_aligned1 = .{1};
    warn("aligned val {}\n", .{ x[0] });
}
```

However the original problem is not fixed since `@sizeOf(c._comfirm_align1) == 8`.

**Comment by Vexu** [comment]
After #4703 `@sizeOf(_comfirm_align1) == 7` if you add the align attribute directly to the structs fields.
```c
struct _comfirm_align1 {
    __attribute__((aligned(1))) U8 a;
    __attribute__((aligned(1))) U16 b;
    __attribute__((aligned(1))) U32 c;
};

```
```zig
pub const struct__comfirm_align1 = extern struct {
    a: U8 align(1),
    b: U16 align(1),
    c: U32 align(1),
};
```
