### ISSUE TITLE
Android link error: relocation R_ARM_TLS_LE32 against tl.foo cannot be used with -shared

### ISSUE THREAD

**Issue by tuket** [ziglang/zig#17575]
### Zig Version

0.12.0-dev.983+78f2ae7f2

### Steps to Reproduce and Observed Behavior

Take this program:

```zig
// tl.zig
const std = @import("std");

threadlocal var foo: std.Thread.Id = 0;

export fn setFoo() void {
    foo = std.Thread.getCurrentId();
}

export fn getFoo() std.Thread.Id {
    return foo;
}
```

We can build a shared lib for linux with the following command:

```
zig.exe build-lib -target arm-linux -dynamic -fPIC tl.zig
```

The previous command compiles fine.

Now if we change `arm-linux` to `arm-linux-android`:

```
zig.exe build-lib -target arm-linux-android -dynamic -fPIC tl.zig
```

We get the following compile error:

```
error: ld.lld: relocation R_ARM_TLS_LE32 against tl.foo cannot be used with -shared
    note: defined in libtl.so.o
    note: referenced by tl.zig:0
    note:               libtl.so.o:(setFoo)
error: ld.lld: relocation R_ARM_TLS_LE32 against tl.foo cannot be used with -shared
    note: defined in libtl.so.o
    note: referenced by tl.zig:0
    note:               libtl.so.o:(getFoo)
error: ld.lld: relocation R_ARM_TLS_LE32 against Thread.LinuxThreadImpl.tls_thread_id cannot be used with -shared
    note: defined in libtl.so.o
    note: referenced by Thread.zig:0 (C:\Users\tuket\Documents\APPS\zig_experimental\lib\std/Thread.zig:0)
    note:               libtl.so.o:(Thread.LinuxThreadImpl.getCurrentId)
error: ld.lld: relocation R_ARM_TLS_LE32 against debug.panic_stage cannot be used with -shared
    note: defined in libtl.so.o
    note: referenced by debug.zig:0 (C:\Users\tuket\Documents\APPS\zig_experimental\lib\std/debug.zig:0)
    note:               libtl.so.o:(debug.panicImpl)
```

However, if we run the same command with zig 0.11.0, it compiles fine.

### Expected Behavior

I'm not certain what should be the expected behavior, but it's weird that it used to work and now it doesn't.

This is preventing me from compiling Android apps.

For this bud report, I tried to make the program as simple as possible.

In my more elaborate Android program, I wasn't actually using the `std.Thread.getCurrentId()` function. In fact, when I would add the "-Drelease" flag to zig, the compiler error would go away (probably due to unused code elimination).

**Comment by tuket** [comment]
I think I found something interesting [here](https://github.com/llvm/llvm-project/issues/55909).

> Right. -fpie/-fPIE compiled object files cannot be linked in -shared mode.

As far as I know, for shared libraries I need the `PIC` (position independent code) flag but not the `PIE` (position independent executable) flag.

So I tried to to use `-fno-PIE` to make sure PIE is not used.

```
$ zig build-lib -target arm-linux-android -dynamic -fPIC -fno-PIE tl.zig
```

And I get this error:

```
error: unable to create compilation: TargetRequiresPIE
```

Could it be that zig is unnecessarily forcing PIE?

**Comment by tuket** [comment]
```zig
pub fn requiresPIE(target: std.Target) bool {
    return target.isAndroid() or target.isDarwin() or target.os.tag == .openbsd;
}
```

Why does Android require PIE?

**Comment by rootbeer** [comment]
I believe forcing PIC or PIE need to depend on what the output object is?  I can see for a platform like Android that all executables must be PIE and shared libraries must be PIC.  But from what I can tell (e.g., see https://mropert.github.io/2018/02/02/pic_pie_sanitizers/ and the `pic/PIC/pie/PIE` options in https://gcc.gnu.org/onlinedocs/gcc-7.2.0/gcc/Code-Gen-Options.html#Code-Gen-Options) PIE is only meant to be used when doing the final linking of an executable (or a static library meant to be part of an executable?).  None of the doc I can find explicitly talks about why putting on PIE on a shared object is bad (one would think it harmless), but it seems to mess something up...

Rust has a `relocation-model` option which lays out the different combinations of choices in a more sane and complete way: https://doc.rust-lang.org/rustc/codegen-options/index.html#relocation-model (be sure to scroll down to the "Linking Effects" doc) Again, doesn't say why PIE on shared objects is bad, but does imply that.

**Comment by tuket** [comment]
> I can see for a platform like Android that all executables must be PIE and shared libraries must be PIC

Android executables don't exist AFAIK? Android applications are Java based, and native code is always contained in a dynamic libraries, AFAIK.

Thanks for the links, the are quite interesting.

**Comment by mikdusan** [comment]
We have logic when setting `ld.lld` flags to only use `pie` when producing an executable. This patch adds the corresponding logic to llvm backend.

Can you try this patch?

```diff
diff --git a/src/codegen/llvm.zig b/src/codegen/llvm.zig
index cddd4340d..ea9be5c29 100644
--- a/src/codegen/llvm.zig
+++ b/src/codegen/llvm.zig
@@ -971,7 +971,7 @@ pub const Object = struct {
             builder.llvm.module.?.setModuleDataLayout(target_data);
 
             if (options.pic) builder.llvm.module.?.setModulePICLevel();
-            if (options.pie) builder.llvm.module.?.setModulePIELevel();
+            if (options.pie and options.effectiveOutputMode() == .Exe) builder.llvm.module.?.setModulePIELevel();
             if (code_model != .Default) builder.llvm.module.?.setModuleCodeModel(code_model);
 
             if (options.opt_bisect_limit >= 0) {
```

**Comment by tuket** [comment]
@mikdusan Yes, that fixes the error. Cheers!

**Comment by StrandedSoftwareDeveloper** [comment]
> ```diff
> diff --git a/src/codegen/llvm.zig b/src/codegen/llvm.zig
> index cddd4340d..ea9be5c29 100644
> --- a/src/codegen/llvm.zig
> +++ b/src/codegen/llvm.zig
> @@ -971,7 +971,7 @@ pub const Object = struct {
>              builder.llvm.module.?.setModuleDataLayout(target_data);
>  
>              if (options.pic) builder.llvm.module.?.setModulePICLevel();
> -            if (options.pie) builder.llvm.module.?.setModulePIELevel();
> +            if (options.pie and options.effectiveOutputMode() == .Exe) builder.llvm.module.?.setModulePIELevel();
>              if (code_model != .Default) builder.llvm.module.?.setModuleCodeModel(code_model);
>  
>              if (options.opt_bisect_limit >= 0) {
> ```
This patch works for me too, is there any reason it can't be/hasn't been merged?
Or is there another fix (I notice this issue is closed)?

**Comment by mikdusan** [comment]
> This patch works for me too, is there any reason it can't be/hasn't been merged?
> Or is there another fix (I notice this issue is closed)?

Consider multiple backends then the same logic is copied to each backend.
Instead, the logic was moved to one place, zig’s front end and available to any backends that care about pie.
To be clear, the front end fix was merged, and then a subsequent fix adjusted it to not allow pie for dynamic libs.

**Comment by geooot** [comment]
I just wanted to comment in here that I am facing this issue still with my android builds [[Repo here]](https://github.com/geooot/zig-sokol-crossplatform-starter). 

In my build configuration, I build two static libraries and then link them together into one dynamic library. Here are generally the build steps:
1. build the app library: which contains the main business logic
2. build the sokol library: which contains the app framework and graphics apis (basically the engine)
3. link them together into one dynamic library to be loaded in by NativeActivity.

I end up getting an error on step 3
```
error: ld.lld: relocation R_AARCH64_TLSLE_ADD_TPREL_HI12 against debug.panic_stage cannot be used with -shared
    note: defined in /Users/george/projects/zig-sokol-crossplatform-starter/zig-cache/o/c22611fb108ffe2a286abe0c568edcbd/libMyApp_aarch64-linux-android.a(/Users/george/projects/zig-sokol-crossplatform-starter/zig-cache/o/c22611fb108ffe2a286abe0c568edcbd/libMyApp_aarch64-linux-android.a.o)
    note: referenced by debug.zig:399 (/Users/george/bin/lib/std/debug.zig:399)
    note:               /Users/george/projects/zig-sokol-crossplatform-starter/zig-cache/o/c22611fb108ffe2a286abe0c568edcbd/libMyApp_aarch64-linux-android.a.o:(debug.panicImpl) in archive /Users/george/projects/zig-sokol-crossplatform-starter/zig-cache/o/c22611fb108ffe2a286abe0c568edcbd/libMyApp_aarch64-linux-android.a
```
[[Full Log]](https://gist.github.com/geooot/276b23872e2e1ab53cecfe4507b6ea7d)

With some print debugging i figured out that steps 1 and 2 are being built with PIE enabled which causes the link step to fail on step 3 when making the dynamic libary.

[This patch](https://github.com/ziglang/zig/issues/17575#issuecomment-1768805247) worked for me, but of course, this probably has other consequences for other backends.

I made a PR (#18150) with a fix that I think addresses the issue (i could be wrong ofc). I noticed that PIE was enabled for static libary builds, it was only disabled for dynamic libraries specifically. My intuition is that PIE only applies to executables so I changed the logic accordingly.

**Comment by rsepassi** [comment]
I'm hitting the same issue as @geooot on v0.12.0. @mikdusan is this a different issue? Should this bug be re-opened or should I file a new one?

**Comment by mikdusan** [comment]
@rsepassi,

The fixes are active in `0.12.0`. If these errors are present it seems `non-PIC` `.o` code is getting used somehow, either directly for the dynamic lib step, or indirectly via `.a` steps.

**Comment by rsepassi** [comment]
Hmm...I have a series of .a builds, all built with `zig build-lib -fPIC`, so I don't see where non-PIC code would be coming in; anything else I need to be doing?

**Comment by mikdusan** [comment]
@rsepassi, ah ok I missed that the behaviour changes when ABI=android in target. This looks to me like a bug.

**Comment by rsepassi** [comment]
Thanks for taking another look. I don't know enough to really be able to say whether those are the bugs, but from an outside perspective, I'd expect to be able to compile N static libraries with -fPIC and then create a dynamic library which links them. I'll leave it to you to decide how to manage the GH issue(s) but do let me know if you'd like me to file an issue.

**Comment by nuxusr** [comment]
Still hitting this on latest master but code is a little different and the change that made it work for me was

![Image](https://github.com/user-attachments/assets/629e0dcb-8116-45f9-aa49-18fdbbf26fdb)
