### ISSUE TITLE
Error message for calling `std.debug.print` with too few arguments does not include the line number of the error

### ISSUE THREAD

**Issue by danvk** [ziglang/zig#18485]
### Zig Version

0.11.0

### Steps to Reproduce and Observed Output

When you call `std.debug.print` with too few arguments:

```zig
std.debug.print("All your {s} are belong to us.\n", .{});  // <-- missing argument
```

The resulting error message does not include the line on which the error occured:

```
$ zig build run
zig build-exe zig-print-no-error Debug native: error: the following command failed with 1 compilation errors:
/opt/homebrew/Cellar/zig/0.11.0/bin/zig build-exe /Users/danvk/code/zig-print-no-error/src/main.zig --cache-dir /Users/danvk/code/zig-print-no-error/zig-cache --global-cache-dir /Users/danvk/.cache/zig --name zig-print-no-error --listen=-
Build Summary: 0/5 steps succeeded; 1 failed (disable with --summary none)
run transitive failure
└─ run zig-print-no-error transitive failure
   ├─ zig build-exe zig-print-no-error Debug native 1 errors
   └─ install transitive failure
      └─ install zig-print-no-error transitive failure
         └─ zig build-exe zig-print-no-error Debug native (reused)
/opt/homebrew/Cellar/zig/0.11.0/lib/zig/std/fmt.zig:182:13: error: too few arguments
            @compileError("too few arguments");
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Here's the full source code for this example, it's just a tweak to what you get by running `zig init-exe`:

```zig
const std = @import("std");

pub fn main() !void {
    // Prints to stderr (it's a shortcut based on `std.io.getStdErr()`)
    std.debug.print("All your {s} are belong to us.\n", .{});

    // stdout is for the actual output of your application, for example if you
    // are implementing gzip, then only the compressed bytes should be sent to
    // stdout, not any debugging messages.
    const stdout_file = std.io.getStdOut().writer();
    var bw = std.io.bufferedWriter(stdout_file);
    const stdout = bw.writer();

    try stdout.print("Run `zig build test` to run the tests.\n", .{});

    try bw.flush(); // don't forget to flush!
}

test "simple test" {
    var list = std.ArrayList(i32).init(std.testing.allocator);
    defer list.deinit(); // try commenting this out and see if zig detects the memory leak!
    try list.append(42);
    try std.testing.expectEqual(@as(i32, 42), list.pop());
}
```

### Expected Output

I'd expect the error message to include the line number of the offending statement. For example, failing to pass the second argument `std.debug.print` shows a more helpful error message which, critically, mentions `src/main.zig:5:14`:

```
$ zig build run
zig build-exe zig-print-no-error Debug native: error: the following command failed with 1 compilation errors:
...
src/main.zig:5:14: error: expected 2 argument(s), found 1
    std.debug.print("All your {s} are belong to us.\n");
    ~~~~~~~~~^~~~~~
/opt/homebrew/Cellar/zig/0.11.0/lib/zig/std/debug.zig:86:5: note: function declared here
pub fn print(comptime fmt: []const u8, args: anytype) void {
~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
    callMain: /opt/homebrew/Cellar/zig/0.11.0/lib/zig/std/start.zig:574:32
    initEventLoopAndCallMain: /opt/homebrew/Cellar/zig/0.11.0/lib/zig/std/start.zig:508:34
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

If you pass too many arguments, rather than too few:

```
- std.debug.print("All your {s} are belong to us.\n", .{"codebase"});
+ std.debug.print("All your {s} are belong to us.\n", .{ "codebase", "second" });
```

Then the error message also doesn't include the line number, but at least it includes the format string, which gives you a hint of where to look in your source code:

```
$ zig build run
...
/opt/homebrew/Cellar/zig/0.11.0/lib/zig/std/fmt.zig:202:18: error: unused argument in 'All your {s} are belong to us.
                                                                   '
            1 => @compileError("unused argument in '" ++ fmt ++ "'"),
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by xdBronch** [comment]
this is a bug in 0.11, fixed in master

**Comment by xdBronch** [comment]
even though the main issue here is fixed i adjusted my pr https://github.com/ziglang/zig/pull/18349 to add a more helpful error message for this case

**Comment by danvk** [comment]
Thanks @xdBronch. Just to make sure I understand your PR, it still won't report the relevant error line but it will at least include the format string in the error message?

**Comment by xdBronch** [comment]
on the master branch (0.12-dev) it should already report the relevant line, at the very least if `-freference-trace` is included, it not doing so is/was a bug with 0.11. but yes, my pr simply includes the format string as well
