### ISSUE TITLE
inlined unreachable function produces warning about invalid debug info

### ISSUE THREAD

**Issue by Techatrix** [ziglang/zig#19093]
### Zig Version

0.12.0-dev.3030+032c2ee9b

### Steps to Reproduce and Observed Behavior

```zig
// file.zig

inline fn panic() void {
    unreachable;
}

const Key = union(enum) {
    foo,
    bar: u32,
};

fn func(key: Key) void {
    switch (key) {
        .foo => panic(),
        .bar => |number| {
            _ = number;
        },
    }
}

test {
    _ = func(.{ .bar = 5 });
}
```

```
zig test file.zig
```

```shell
LLVM Emit Object... mismatched subprogram between llvm.dbg.declare variable and !dbg attachment
  call void @llvm.dbg.declare(metadata ptr %1, metadata !2535, metadata !DIExpression()), !dbg !2529
label %Case1
ptr @file.func
!2535 = !DILocalVariable(name: "number", scope: !2536, file: !225, line: 2, type: !203)
!2517 = distinct !DISubprogram(name: "func", linkageName: "file.func", scope: !225, file: !225, line: 10, type: !2518, scopeLine: 10, flags: DIFlagStaticMember, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !2)
!2529 = !DILocation(line: 2, column: 5, scope: !2530, inlinedAt: !2527)
!2532 = distinct !DISubprogram(name: "panic", linkageName: "file.panic", scope: !225, file: !225, line: 1, type: !2533, scopeLine: 1, flags: DIFlagStaticMember, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !2)
warning: ignoring invalid debug info in BitcodeBuffer
All 1 tests passed.
```
warnings in Zig? 🤔

### Expected Behavior

Make LLVM happy.
```
All 1 tests passed.
```

**Comment by antlilja** [comment]
@jacobly0 This seems to have been fixed at least as of: `0.12.0-dev.3079+a1b083b66`. I would guess it was fixed by mlugg in #19062

**Comment by jacobly0** [comment]
The AIR still has the same bug, so I'm sure you could still reproduce the problem with a different example, such as:
```zig
inline fn panic2() void {
    unreachable;
}

const Key = union(enum) {
    foo,
    bar: u32,
};

fn func(key: Key) void {
    switch (key) {
        .foo => {
            if (key == .foo) panic2();
        },
        .bar => |number| {
            _ = number;
        },
    }
}

export fn entry() void {
    _ = func(.{ .bar = 5 });
}
```
```
$ zig build-obj repro.zig
LLVM Emit Object... mismatched subprogram between llvm.dbg.declare variable and !dbg attachment
  call void @llvm.dbg.declare(metadata ptr %1, metadata !2041, metadata !DIExpression()), !dbg !2039
label %Case1
ptr @repro.func
!2041 = !DILocalVariable(name: "number", scope: !2035, file: !117, line: 2, type: !124)
!2027 = distinct !DISubprogram(name: "func", linkageName: "repro.func", scope: !117, file: !117, line: 10, type: !2028, scopeLine: 10, flags: DIFlagStaticMember, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !2)
!2039 = !DILocation(line: 2, column: 5, scope: !2040, inlinedAt: !2036)
!2040 = distinct !DISubprogram(name: "panic2", linkageName: "repro.panic2", scope: !117, file: !117, line: 1, type: !2023, scopeLine: 1, flags: DIFlagStaticMember, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !2)
warning: ignoring invalid debug info in BitcodeBuffer
```

**Comment by antlilja** [comment]
> The AIR still has the same bug, so I'm sure you could still reproduce the problem with a different example, such as:
> 
> ```zig
> inline fn panic2() void {
>     unreachable;
> }
> 
> const Key = union(enum) {
>     foo,
>     bar: u32,
> };
> 
> fn func(key: Key) void {
>     switch (key) {
>         .foo => {
>             if (key == .foo) panic2();
>         },
>         .bar => |number| {
>             _ = number;
>         },
>     }
> }
> 
> export fn entry() void {
>     _ = func(.{ .bar = 5 });
> }
> ```
> 
> ```
> $ zig build-obj repro.zig
> LLVM Emit Object... mismatched subprogram between llvm.dbg.declare variable and !dbg attachment
>   call void @llvm.dbg.declare(metadata ptr %1, metadata !2041, metadata !DIExpression()), !dbg !2039
> label %Case1
> ptr @repro.func
> !2041 = !DILocalVariable(name: "number", scope: !2035, file: !117, line: 2, type: !124)
> !2027 = distinct !DISubprogram(name: "func", linkageName: "repro.func", scope: !117, file: !117, line: 10, type: !2028, scopeLine: 10, flags: DIFlagStaticMember, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !2)
> !2039 = !DILocation(line: 2, column: 5, scope: !2040, inlinedAt: !2036)
> !2040 = distinct !DISubprogram(name: "panic2", linkageName: "repro.panic2", scope: !117, file: !117, line: 1, type: !2023, scopeLine: 1, flags: DIFlagStaticMember, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !2)
> warning: ignoring invalid debug info in BitcodeBuffer
> ```

You're totally right, my mistake. It seems like it just doesn't reproduce in the original example anymore
