### ISSUE TITLE
reached unreachable code error when calling JSON API with http client

### ISSUE THREAD

**Issue by numeralblue** [ziglang/zig#24880]
### Zig Version

0.15.0-dev.1552+b87b95868

### Steps to Reproduce and Observed Behavior

Call an API with std.http.Client that has a large JSON output that is compressed.

Code:

```zig
pub fn main() !void {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    var client: std.http.Client = .{
        .allocator = allocator,
    };
    defer client.deinit();
    var response: std.Io.Writer.Allocating = .init(allocator);

    const url = "https://api.stlouisfed.org/fred/series/observations?series_id=UNRATE&file_type=json&api_key=f2e9c581283657f47898b9b77732fcad";

    const result = try client.fetch(.{
        .location = .{ .url = url },
        .response_writer = &response.writer,
        .headers = .{ .accept_encoding = .{ .override = "identity" } }
    });

    std.debug.print("status code: {}\n", .{result.status});
    std.debug.print("res: {}\n", .{result});

    const json_data = try std.json.parseFromSliceLeaky(ResponseJson, allocator, response.written(), .{});
    std.debug.print("response data: {}\n", .{json_data});
}

const ResponseJson = struct {
    realtime_start: []const u8,
    realtime_end: []const u8,
    observation_start: []const u8,
    observation_end: []const u8,
    units: []const u8,
    output_type: u32,
    file_type: []const u8,
    order_by: []const u8,
    sort_order: []const u8,
    count: u32,
    offset: u32,
    limit: u32,
    observations: []struct {
        realtime_start: []const u8,
        realtime_end: []const u8,
        date: []const u8,
        value: []const u8,
    }
};

const std = @import("std");
```

A run time error will happen:

```
thread 16812 panic: reached unreachable code
/home/miguel/zig/lib/std/Io/Writer.zig:2322:5: 0x188ebd8 in unreachableDrain (std.zig)
    unreachable;
    ^
/home/miguel/zig/lib/std/Io/Writer.zig:325:35: 0x14e558a in drainPreserve (std.zig)
    assert(0 == try w.vtable.drain(w, &.{""}, 1));
                                  ^
/home/miguel/zig/lib/std/Io/Writer.zig:386:26: 0x14673ff in writableSliceGreedyPreserve (std.zig)
        try drainPreserve(w, preserve_len);
                         ^
/home/miguel/zig/lib/std/Io/Writer.zig:402:56: 0x188f584 in writableSlicePreserve (std.zig)
    const big_slice = try w.writableSliceGreedyPreserve(preserve_len, len);
                                                       ^
/home/miguel/zig/lib/std/compress/flate/Decompress.zig:497:45: 0x188833f in writeMatch (std.zig)
    const dest = try w.writableSlicePreserve(flate.history_len, length);
                                            ^
/home/miguel/zig/lib/std/compress/flate/Decompress.zig:404:39: 0x188c5e1 in streamInner (std.zig)
                        try writeMatch(w, length, distance);
                                      ^
/home/miguel/zig/lib/std/compress/flate/Decompress.zig:256:23: 0x187cb4a in streamFallible (std.zig)
    return streamInner(d, w, limit) catch |err| switch (err) {
                      ^
/home/miguel/zig/lib/std/compress/flate/Decompress.zig:177:23: 0x187d72c in streamIndirectInner (std.zig)
    _ = streamFallible(d, &writer, .limited(writer.buffer.len - writer.end)) catch |err| switch (err) {
                      ^
/home/miguel/zig/lib/std/compress/flate/Decompress.zig:252:31: 0x1891225 in streamIndirect (std.zig)
    return streamIndirectInner(d);
                              ^
/home/miguel/zig/lib/std/Io/Reader.zig:178:34: 0x109b62e in stream (std.zig)
    const n = try r.vtable.stream(r, w, limit);
                                 ^
/home/miguel/zig/lib/std/Io/Reader.zig:257:27: 0x1174985 in streamRemaining (std.zig)
        offset += r.stream(w, .unlimited) catch |err| switch (err) {
                          ^
/home/miguel/zig/lib/std/http/Client.zig:1803:31: 0x116d131 in fetch (std.zig)
    _ = reader.streamRemaining(response_writer) catch |err| switch (err) {
                              ^
/home/miguel/workspace/trade/finch/main3.zig:14:36: 0x1169948 in main (main3.zig)
    const result = try client.fetch(.{
                                   ^
/home/miguel/zig/lib/std/start.zig:627:37: 0x116a739 in posixCallMainAndExit (std.zig)
            const result = root.main() catch |err| {
                                    ^
/home/miguel/zig/lib/std/start.zig:232:5: 0x1169421 in _start (std.zig)
    asm volatile (switch (native_arch) {
    ^
???:?:?: 0x0 in ??? (???)
Aborted                    (core dumped) ./main3
```

### Expected Behavior

fetch should succeed.

workaround:
Set accept encoding to not compress in fetch call.

.headers = .{ .accept_encoding = .{ .override = "identity" } }

discord help link:
https://discord.com/channels/605571803288698900/1406369936313684099

**Comment by andrewrk** [comment]
Hi, thanks for the report, and for putting the `zig version` in there. I fixed a number of bugs in between that version and latest master, so please upgrade and try again. I did try your example just now on my computer on `0.15.0-dev.1597+623290ea9` and it ran successfully.

**Comment by numeralblue** [comment]
> Hi, thanks for the report, and for putting the `zig version` in there. I fixed a number of bugs in between that version and latest master, so please upgrade and try again. I did try your example just now on my computer on `0.15.0-dev.1597+623290ea9` and it ran successfully.

I tried release 0.16.0-dev.23+47a2f2dda and I still get the runtime error. I also compiled zig from source 0.16.0-dev.27+83f773fc6 and I get the error as well. I'm on Arch if that helps.

```
$ ../../zig/build/stage3/bin/zig version
0.16.0-dev.27+83f773fc6
[miguel@sisko temp]$ ../../zig/build/stage3/bin/zig build-exe main3.zig
[miguel@sisko temp]$ ls
main2.zig  main3  main3.zig  main4.zig
[miguel@sisko temp]$ ./main3
thread 543668 panic: reached unreachable code
/home/miguel/workspace/trade/zig/build/stage3/lib/zig/std/Io/Writer.zig:2374:5: 0x1823f59 in unreachableRebase (std.zig)
    unreachable;
    ^
/home/miguel/workspace/trade/zig/build/stage3/lib/zig/std/Io/Writer.zig:338:27: 0x14c3ba0 in rebase (std.zig)
    return w.vtable.rebase(w, preserve, unused_capacity_len);
                          ^
/home/miguel/workspace/trade/zig/build/stage3/lib/zig/std/Io/Writer.zig:412:15: 0x144966a in writableSliceGreedyPreserve (std.zig)
    try rebase(w, preserve, minimum_len);
              ^
/home/miguel/workspace/trade/zig/build/stage3/lib/zig/std/Io/Writer.zig:426:56: 0x1825d04 in writableSlicePreserve (std.zig)
    const big_slice = try w.writableSliceGreedyPreserve(preserve, len);
                                                       ^
/home/miguel/workspace/trade/zig/build/stage3/lib/zig/std/compress/flate/Decompress.zig:497:45: 0x181d67f in writeMatch (std.zig)
    const dest = try w.writableSlicePreserve(flate.history_len, length);
                                            ^
/home/miguel/workspace/trade/zig/build/stage3/lib/zig/std/compress/flate/Decompress.zig:404:39: 0x1821921 in streamInner (std.zig)
                        try writeMatch(w, length, distance);
                                      ^
/home/miguel/workspace/trade/zig/build/stage3/lib/zig/std/compress/flate/Decompress.zig:256:23: 0x1811e6a in streamFallible (std.zig)
    return streamInner(d, w, limit) catch |err| switch (err) {
                      ^
/home/miguel/workspace/trade/zig/build/stage3/lib/zig/std/compress/flate/Decompress.zig:179:23: 0x1812a5f in streamIndirectInner (std.zig)
    _ = streamFallible(d, &writer, .limited(writer.buffer.len - writer.end)) catch |err| switch (err) {
                      ^
/home/miguel/workspace/trade/zig/build/stage3/lib/zig/std/compress/flate/Decompress.zig:252:31: 0x1827b45 in streamIndirect (std.zig)
    return streamIndirectInner(d);
                              ^
/home/miguel/workspace/trade/zig/build/stage3/lib/zig/std/Io/Reader.zig:178:34: 0x1098a3e in stream (std.zig)
    const n = try r.vtable.stream(r, w, limit);
                                 ^
/home/miguel/workspace/trade/zig/build/stage3/lib/zig/std/Io/Reader.zig:257:27: 0x10cf455 in streamRemaining (std.zig)
        offset += r.stream(w, .unlimited) catch |err| switch (err) {
                          ^
/home/miguel/workspace/trade/zig/build/stage3/lib/zig/std/http/Client.zig:1834:31: 0x116691d in fetch (std.zig)
    _ = reader.streamRemaining(response_writer) catch |err| switch (err) {
                              ^
/home/miguel/workspace/trade/finch/temp/main3.zig:14:36: 0x1163078 in main (main3.zig)
    const result = try client.fetch(.{
                                   ^
/home/miguel/workspace/trade/zig/build/stage3/lib/zig/std/start.zig:627:37: 0x1163e69 in posixCallMainAndExit (std.zig)
            const result = root.main() catch |err| {
                                    ^
/home/miguel/workspace/trade/zig/build/stage3/lib/zig/std/start.zig:232:5: 0x1162b51 in _start (std.zig)
    asm volatile (switch (native_arch) {
    ^
???:?:?: 0x0 in ??? (???)
Aborted                    (core dumped) ./main3
```

**Comment by numeralblue** [comment]
I reproduced the issue on an Ubuntu VM with zig version 0.16.0-dev.23+47a2f2dda.

```
thread 2307 panic: reached unreachable code
/root/zig/lib/std/Io/Writer.zig:2374:5: 0x1878d29 in unreachableRebase (std.zig)
    unreachable;
    ^
/root/zig/lib/std/Io/Writer.zig:338:27: 0x14c82b0 in rebase (std.zig)
    return w.vtable.rebase(w, preserve, unused_capacity_len);
                          ^
/root/zig/lib/std/Io/Writer.zig:412:15: 0x144dd7a in writableSliceGreedyPreserve (std.zig)
    try rebase(w, preserve, minimum_len);
              ^
/root/zig/lib/std/Io/Writer.zig:426:56: 0x187aad4 in writableSlicePreserve (std.zig)
    const big_slice = try w.writableSliceGreedyPreserve(preserve, len);
                                                       ^
/root/zig/lib/std/compress/flate/Decompress.zig:497:45: 0x187244f in writeMatch (std.zig)
    const dest = try w.writableSlicePreserve(flate.history_len, length);
                                            ^
/root/zig/lib/std/compress/flate/Decompress.zig:404:39: 0x18766f1 in streamInner (std.zig)
                        try writeMatch(w, length, distance);
                                      ^
/root/zig/lib/std/compress/flate/Decompress.zig:256:23: 0x1866c3a in streamFallible (std.zig)
    return streamInner(d, w, limit) catch |err| switch (err) {
                      ^
/root/zig/lib/std/compress/flate/Decompress.zig:179:23: 0x186782f in streamIndirectInner (std.zig)
    _ = streamFallible(d, &writer, .limited(writer.buffer.len - writer.end)) catch |err| switch (err) {
                      ^
/root/zig/lib/std/compress/flate/Decompress.zig:252:31: 0x187c915 in streamIndirect (std.zig)
    return streamIndirectInner(d);
                              ^
/root/zig/lib/std/Io/Reader.zig:178:34: 0x1099fbe in stream (std.zig)
    const n = try r.vtable.stream(r, w, limit);
                                 ^
/root/zig/lib/std/Io/Reader.zig:257:27: 0x10d1bf5 in streamRemaining (std.zig)
        offset += r.stream(w, .unlimited) catch |err| switch (err) {
                          ^
/root/zig/lib/std/http/Client.zig:1834:31: 0x116b0fd in fetch (std.zig)
    _ = reader.streamRemaining(response_writer) catch |err| switch (err) {
                              ^
/root/main3.zig:14:36: 0x1167858 in main (main3.zig)
    const result = try client.fetch(.{
                                   ^
/root/zig/lib/std/start.zig:627:37: 0x1168649 in posixCallMainAndExit (std.zig)
            const result = root.main() catch |err| {
                                    ^
/root/zig/lib/std/start.zig:232:5: 0x1167331 in _start (std.zig)
    asm volatile (switch (native_arch) {
    ^
???:?:?: 0x0 in ??? (???)
Aborted (core dumped)
```

**Comment by numeralblue** [comment]
It looks like I pasted the workaround code that works. Sorry about that. This is the code that does not work:
You will notice that the headers are not set in this one.

```zig
pub fn main() !void {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    var client: std.http.Client = .{
        .allocator = allocator,
    };
    defer client.deinit();
    var response: std.Io.Writer.Allocating = .init(allocator);

    const url = "https://api.stlouisfed.org/fred/series/observations?series_id=UNRATE&file_type=json&api_key=f2e9c581283657f47898b9b77732fcad";

    const result = try client.fetch(.{
        .location = .{ .url = url },
        .response_writer = &response.writer,
    });

    std.debug.print("status code: {}\n", .{result.status});
    std.debug.print("res: {}\n", .{result});

    const json_data = try std.json.parseFromSliceLeaky(ResponseJson, allocator, response.written(), .{});
    std.debug.print("response data: {}\n", .{json_data});
}

const ResponseJson = struct {
    realtime_start: []const u8,
    realtime_end: []const u8,
    observation_start: []const u8,
    observation_end: []const u8,
    units: []const u8,
    output_type: u32,
    file_type: []const u8,
    order_by: []const u8,
    sort_order: []const u8,
    count: u32,
    offset: u32,
    limit: u32,
    observations: []struct {
        realtime_start: []const u8,
        realtime_end: []const u8,
        date: []const u8,
        value: []const u8,
    }
};

const std = @import("std");
```
