### ISSUE TITLE
add macosx libc as a cross compilation target

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#2875]
Extracted from #514.

We don't need any startup files for this one, but we do need headers.

**Comment by andrewrk** [comment]
Done by @kubkon in #6752

**Comment by chadbrewbaker** [comment]
It is still missing compile time specialization. Since MacOS can’t agree on a fixed interface. You have an optional check at startup to make sure Apple hasn’t broken the interface, if it did you change the function pointers to hit libsystem instead of compile time specialized code. https://github.com/apple-oss-distributions/Libc
