### ISSUE TITLE
 Colors in error output no longer work in Windows Command Prompt

### ISSUE THREAD

**Issue by CurtisFenner** [ziglang/zig#3147]
I noticed that colors in output have became broken somewhere between 6ab8b2a and 57b90d2.

It appears that colors stopped working when #2991 was merged. (They work on `e68fee3`)

**Comment by andrewrk** [comment]
Is it fixed now that #2991 is reverted?

**Comment by raulgrell** [comment]
The binary at https://ziglang.org/builds/zig-windows-x86_64-0.4.0+ec6f15b0.zip still does not have color - I'm not sure if it's the latest master

![image](https://user-images.githubusercontent.com/179686/64077808-af1f4400-cccb-11e9-9b65-f3b53ad0d387.png)

**Comment by andrewrk** [comment]
ec6f15b0 is the one before the revert

**Comment by CurtisFenner** [comment]
I can confirm colors are working at `0.4.0+8b1900e`.

**Comment by raulgrell** [comment]
I can confirm that it is fixed in master:

![image](https://user-images.githubusercontent.com/179686/64080608-48f7e880-ccee-11e9-926f-e249a65663d4.png)
