### ISSUE TITLE
Wrong type name is inferred

### ISSUE THREAD

**Issue by MasterQ32** [ziglang/zig#3693]
Some types have "incorrect" names as in the namespace reported for the type does not match. Prominent example: `std.mem.Allocator.Error` is reported as `std.mem.Error`.

Declaration site:
```zig
// mem.zig

pub const Allocator = struct {
    pub const Error = error{OutOfMemory};
    …
};
```

Reported in error message:
```
error: expected type 'fn(*std.mem.Allocator, []u8, u29, usize, u29) std.mem.Error![]u8', found 'fn() std.mem.Error![]u8'
```

[Reported in docs](https://ziglang.org/documentation/master/std/#std;mem.Allocator.Error):
```
mem.Error (ErrorSet)
Errors
OutOfMemory
```

**Comment by SpexGuy** [comment]
I think this is now fixed.
```zig
const Error = @import("std").mem.Allocator.Error;
pub fn main() void {
    @compileLog(@typeName(Error));
    @compileLog(@typeName(fn(Error)void));
}
```
logs
```
| *"std.mem.Allocator.Error"
| *"fn(std.mem.Allocator.Error) void"
```

**Comment by Vexu** [comment]
The example with `mem.Allocator.Error` only works now because `Allocator` has been moved to its own file. If you add a namespace to `std.mem` the issue still persists:
```zig
// add to mem.zig
pub const namespace = struct {
    pub const Error = error{ Foo };
};

const Error = @import("std").mem.namespace.Error;
pub fn main() void {
    @compileLog(@typeName(Error)); // | *"std.mem.Error"
    @compileLog(@typeName(fn(Error)void)); // | *"fn(std.mem.Error) void"
}
```
