### ISSUE TITLE
@Type builtin not picking up sentinel value from @typeInfo

### ISSUE THREAD

**Issue by marler8997** [ziglang/zig#3828]
The following program shows that `@Type` does not maintain the sentinel value from typeinfo:
```zig
const std = @import("std");

fn testTypes(comptime types: []const type) void {
    var errorCount : usize = 0;
    inline for (types) |Expected| {
        const Actual = @Type(@typeInfo(Expected));
        if (Expected != Actual) {
            std.debug.warn("expected '{}'\n", @typeName(Expected));
            std.debug.warn("actual   '{}'\n", @typeName(Actual));
            errorCount += 1;
        }
    }
    if (errorCount > 0) {
        std.debug.warn("{}/{} test cases failed\n", errorCount, types.len);
    }
}

pub fn main() void {
    testTypes(&[_]type {
        [11:0]u8, [4:10]u8,
        [*:0]u8,                             [*:0]const u8,
        [*:0]volatile u8,                    [*:0]const volatile u8,
        [*:0]align(4) u8,                    [*:0]align(4) const u8,
        [*:0]align(4) volatile u8,           [*:0]align(4) const volatile u8,
        [*:0]align(8) u8,                    [*:0]align(8) const u8,
        [*:0]align(8) volatile u8,           [*:0]align(8) const volatile u8,
        [*:0]allowzero u8,                   [*:0]allowzero const u8,
        [*:0]allowzero volatile u8,          [*:0]allowzero const volatile u8,
        [*:0]allowzero align(4) u8,          [*:0]allowzero align(4) const u8,
        [*:0]allowzero align(4) volatile u8, [*:0]allowzero align(4) const volatile u8,
        [*:5]allowzero align(4) volatile u8, [*:5]allowzero align(4) const volatile u8,
        [:0]u8,                              [:0]const u8,
        [:0]volatile u8,                     [:0]const volatile u8,
        [:0]align(4) u8,                     [:0]align(4) const u8,
        [:0]align(4) volatile u8,            [:0]align(4) const volatile u8,
        [:0]align(8) u8,                     [:0]align(8) const u8,
        [:0]align(8) volatile u8,            [:0]align(8) const volatile u8,
        [:0]allowzero u8,                    [:0]allowzero const u8,
        [:0]allowzero volatile u8,           [:0]allowzero const volatile u8,
        [:0]allowzero align(4) u8,           [:0]allowzero align(4) const u8,
        [:0]allowzero align(4) volatile u8,  [:0]allowzero align(4) const volatile u8,
        [:4]allowzero align(4) volatile u8,  [:4]allowzero align(4) const volatile u8,
    });
}

```

**Comment by andrewrk** [comment]
Fixed by #3855.

**Comment by marler8997** [comment]
@andrewrk I just built master and ran this test and it still fails 46 out of 46 cases.  Can you please reopen (I can't reopen for some reason)?  Here is the output with the latest zig compiler (05fc4d34a93d1e8fd4a107cb17c9d4fd7ffc29bc)
```
expected '[11:0]u8'
actual   '[11]u8'
expected '[4:10]u8'
actual   '[4]u8'
expected '[*:0]u8'
actual   '[*]u8'
expected '[*:0]const u8'
actual   '[*]const u8'
expected '[*:0]volatile u8'
actual   '[*]volatile u8'
expected '[*:0]const volatile u8'
actual   '[*]const volatile u8'
expected '[*:0]align(4) u8'
actual   '[*]align(4) u8'
expected '[*:0]align(4) const u8'
actual   '[*]align(4) const u8'
expected '[*:0]align(4) volatile u8'
actual   '[*]align(4) volatile u8'
expected '[*:0]align(4) const volatile u8'
actual   '[*]align(4) const volatile u8'
expected '[*:0]align(8) u8'
actual   '[*]align(8) u8'
expected '[*:0]align(8) const u8'
actual   '[*]align(8) const u8'
expected '[*:0]align(8) volatile u8'
actual   '[*]align(8) volatile u8'
expected '[*:0]align(8) const volatile u8'
actual   '[*]align(8) const volatile u8'
expected '[*:0]allowzero u8'
actual   '[*]allowzero u8'
expected '[*:0]const allowzero u8'
actual   '[*]const allowzero u8'
expected '[*:0]volatile allowzero u8'
actual   '[*]volatile allowzero u8'
expected '[*:0]const volatile allowzero u8'
actual   '[*]const volatile allowzero u8'
expected '[*:0]align(4) allowzero u8'
actual   '[*]align(4) allowzero u8'
expected '[*:0]align(4) const allowzero u8'
actual   '[*]align(4) const allowzero u8'
expected '[*:0]align(4) volatile allowzero u8'
actual   '[*]align(4) volatile allowzero u8'
expected '[*:0]align(4) const volatile allowzero u8'
actual   '[*]align(4) const volatile allowzero u8'
expected '[*:5]align(4) volatile allowzero u8'
actual   '[*]align(4) volatile allowzero u8'
expected '[*:5]align(4) const volatile allowzero u8'
actual   '[*]align(4) const volatile allowzero u8'
expected '[:0]u8'
actual   '[]u8'
expected '[:0]const u8'
actual   '[]const u8'
expected '[:0]volatile u8'
actual   '[]volatile u8'
expected '[:0]const volatile u8'
actual   '[]const volatile u8'
expected '[:0]align(4) u8'
actual   '[]align(4) u8'
expected '[:0]align(4) const u8'
actual   '[]align(4) const u8'
expected '[:0]align(4) volatile u8'
actual   '[]align(4) volatile u8'
expected '[:0]align(4) const volatile u8'
actual   '[]align(4) const volatile u8'
expected '[:0]align(8) u8'
actual   '[]align(8) u8'
expected '[:0]align(8) const u8'
actual   '[]align(8) const u8'
expected '[:0]align(8) volatile u8'
actual   '[]align(8) volatile u8'
expected '[:0]align(8) const volatile u8'
actual   '[]align(8) const volatile u8'
expected '[:0]allowzero u8'
actual   '[]allowzero u8'
expected '[:0]const allowzero u8'
actual   '[]const allowzero u8'
expected '[:0]volatile allowzero u8'
actual   '[]volatile allowzero u8'
expected '[:0]const volatile allowzero u8'
actual   '[]const volatile allowzero u8'
expected '[:0]align(4) allowzero u8'
actual   '[]align(4) allowzero u8'
expected '[:0]align(4) const allowzero u8'
actual   '[]align(4) const allowzero u8'
expected '[:0]align(4) volatile allowzero u8'
actual   '[]align(4) volatile allowzero u8'
expected '[:0]align(4) const volatile allowzero u8'
actual   '[]align(4) const volatile allowzero u8'
expected '[:4]align(4) volatile allowzero u8'
actual   '[]align(4) volatile allowzero u8'
expected '[:4]align(4) const volatile allowzero u8'
actual   '[]align(4) const volatile allowzero u8'
46/46 test cases failed
```
