### ISSUE TITLE
Generated docs not working anymore for my project

### ISSUE THREAD

**Issue by kristoff-it** [ziglang/zig#4062]
The project in question: https://github.com/kristoff-it/zig-okredis
To generate the docs you can run `zig build docs`.

Here you can find a copy that generated correctly: https://kristoff.it/zig-okredis/#root
You can see from that page that the zig compiler was updated to this commit https://github.com/ziglang/zig/commit/c3d8b1ffebb94d180c382bd74128d17dc21c1392.

At one point after that commit the behavior changed and now the docs come out empty (i.e., only contain the stdlib stuff that was referenced).

**Comment by andrewrk** [comment]
Fixed by @FireFox317 in e095475d922672c7c502c81477bfdcb973e30352.

BTW @kristoff-it you may be interested in this pattern:

https://github.com/ziglang/zig/blob/378bf1c3b71fdcc823fb9a5382400ec0a659fc00/lib/std/std.zig#L77

I don't see this as a long term solution, but for now, this can help you get better quality generated docs.

**Comment by kristoff-it** [comment]
Thank you @andrewrk for the suggestion.

Now the process completes successfully but the resulting document is still buggy. 
I'm not referring to small things or missing pieces, but rather that when no section is selected (i.e. no url fragment) I see my declarations, while when `root` is selected, I only see a bogus main function. Trying to navigate my declarations from the first state doesn't work.

Should I open a new issue for that?

**Comment by andrewrk** [comment]
I'm aware of that issue but I don't think there is a GitHub issue to track it - so feel free to do that.

I'm planning to solve that along with a second iteration of how the URL works (will break current URLs)

**Comment by kristoff-it** [comment]
Ok, thanks.
